#ifndef REL_OPTION_GLOBALS_H
#define REL_OPTION_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module option`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_4_bss_0: .bss size 0x2, referenced by 39 functions, shape {'object': 762}
extern u16 lbl_4_bss_0;

// lbl_4_data_0: .data size 0xC, referenced by 17 functions, shape {'object': 49}
extern u8 lbl_4_data_0[0xC];

// lbl_4_bss_8: .bss size 0x4, referenced by 14 functions, shape {'object': 14}
extern u32 lbl_4_bss_8;

// lbl_4_bss_5680: .bss size 0x4, referenced by 8 functions, shape {'object': 112, 'pointer': 28}
typedef struct {
    u32 unk_0;  // 11 loads, 6 stores
    u32 unk_4;  // 1 loads, 1 stores
    u32 unk_8;  // 4 loads, 1 stores
    u8 unk_C;  // 8 loads, 1 stores
    u8 unk_D;  // 5 loads, 4 stores
    u8 unk_E;  // 10 loads, 3 stores
    u8 unk_F;  // 3 loads, 12 stores
    u8 unk_10;  // 1 loads, 0 stores
    u8 unk_11;  // 2 loads, 1 stores
    u16 unk_12;  // 3 loads, 3 stores
    u8 unk_14;  // 2 loads, 2 stores
    u8 unk_15;  // 2 loads, 2 stores
    u8 unk_16;  // 2 loads, 2 stores
    u8 unk_17;  // 2 loads, 2 stores
    u32 unk_18;  // 1 loads, 1 stores
    u32 unk_1C;  // 1 loads, 1 stores
    u32 unk_20;  // 3 loads, 2 stores
    u8 pad_24[0x4];
    u8 unk_28;  // 1 loads, 0 stores
    u8 pad_29[0xD];
    u8 unk_36;  // 2 loads, 1 stores
    u8 unk_37;  // 0 loads, 1 stores
    u8 pad_38[0x2];
    u8 unk_3A;  // 2 loads, 2 stores
    u8 unk_3B;  // 5 loads, 2 stores
    u32 unk_3C;  // 4 loads, 2 stores
} Obj_4_bss_5680_Target;
extern Obj_4_bss_5680_Target *lbl_4_bss_5680;

// lbl_4_bss_5630: .bss size 0x48, referenced by 6 functions, shape {'object': 5}
typedef struct {
    u32 unk_0;  // 0 loads, 3 stores
    u8 unk_4;  // 0 loads, 1 stores
    u8 pad_5[0x1D];
    u8 unk_22;  // 1 loads, 0 stores
    u8 pad_23[0x25];
} Obj_4_bss_5630;
extern Obj_4_bss_5630 lbl_4_bss_5630;

// lbl_4_bss_2: .bss size 0x1, referenced by 5 functions, shape {'object': 10}
extern u8 lbl_4_bss_2;

// lbl_4_data_2F78: .data size 0xA0, referenced by 5 functions, shape {}
extern u8 lbl_4_data_2F78[0xA0];

// lbl_4_data_2F1C: .data size 0x4, referenced by 4 functions, shape {'object': 4}
extern u32 lbl_4_data_2F1C;

// lbl_4_bss_5684: .bss size 0x1, referenced by 3 functions, shape {'object': 3}
extern u8 lbl_4_bss_5684;

// lbl_4_bss_4: .bss size 0x4, referenced by 2 functions, shape {'object': 2}
extern u32 lbl_4_bss_4;

// lbl_4_bss_10: .bss size 0xB4, referenced by 2 functions, shape {'object': 8}
typedef struct {
    u16 unk_0;  // 4 loads, 4 stores
    u8 pad_2[0xB2];
} Obj_4_bss_10;
extern Obj_4_bss_10 lbl_4_bss_10;

// lbl_4_bss_C4: .bss size 0x5554, referenced by 2 functions, shape {'object': 16}
typedef struct {
    u8 pad_0[0x2];
    u16 unk_2;  // 1 loads, 1 stores
    u16 unk_4;  // 1 loads, 1 stores
    u16 unk_6;  // 1 loads, 1 stores
    u32 unk_8;  // 1 loads, 1 stores
    u32 unk_C;  // 1 loads, 1 stores
    u32 unk_10;  // 1 loads, 1 stores
    u32 unk_14;  // 1 loads, 1 stores
    u32 unk_18;  // 1 loads, 1 stores
    u8 pad_1C[0x5538];
} Obj_4_bss_C4;
extern Obj_4_bss_C4 lbl_4_bss_C4;

// lbl_4_data_2F00: .data size 0x1C, referenced by 2 functions, shape {'object': 6}
typedef struct {
    u8 pad_0[0x18];
    u32 unk_18;  // 3 loads, 1 stores
} Obj_4_data_2F00;
extern Obj_4_data_2F00 lbl_4_data_2F00;

// lbl_4_bss_5685: .bss size 0x1, referenced by 2 functions, shape {'object': 6}
extern u8 lbl_4_bss_5685;

#endif  // REL_OPTION_GLOBALS_H
