#ifndef REL_OPTION_NAME_ENTRY_H
#define REL_OPTION_NAME_ENTRY_H

#include "types.h"
#include "rel/option/globals.h"

// Generated by `fzgx headers --module option --tu name_entry.c`: globals of name_entry.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_4_data_3018: .data size 0x40, 1 refs from name_entry.c (own data block)
extern u8 lbl_4_data_3018[0x40];

#endif  // REL_OPTION_NAME_ENTRY_H
