/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_4DB0[41];
extern char lbl_10_data_4DDC[18];
extern char lbl_10_data_4DF0[18];
extern char lbl_10_data_4E04[18];
extern char lbl_10_data_4E18[18];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4DB0[41] __attribute__((aligned(8))) = "Please set up your F-ZERO LICENSE CARD. ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4DDC[18] __attribute__((aligned(4))) = "PLEASE_SET_UP GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4DF0[18] __attribute__((aligned(8))) = "PLEASE_SET_UP FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4E04[18] __attribute__((aligned(4))) = "PLEASE_SET_UP SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4E18[18] __attribute__((aligned(8))) = "PLEASE_SET_UP ITA";
#pragma explicit_zero_data reset
