/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_10_bss_3C0[74736];



__declspec(section ".data") u32 lbl_10_bss_3C0[74736] __attribute__((aligned(32)));
