/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2BE8[5];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2BE8[5] __attribute__((aligned(8))) = "E3-1";
#pragma explicit_zero_data reset
