/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_10D0[39];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_10D0[39] __attribute__((aligned(8))) = "Your play data and your machine data. ";
#pragma explicit_zero_data reset
