/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1B48[19];
extern char lbl_10_data_1B5C[22];
extern char lbl_10_data_1B74[22];
extern char lbl_10_data_1B8C[22];
extern char lbl_10_data_1BA4[22];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1B48[19] __attribute__((aligned(8))) = "There is no data. ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1B5C[22] __attribute__((aligned(4))) = "GER There is no data.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1B74[22] __attribute__((aligned(4))) = "FRE There is no data.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1B8C[22] __attribute__((aligned(4))) = "SPA There is no data.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1BA4[22] __attribute__((aligned(4))) = "ITA There is no data.";
#pragma explicit_zero_data reset
