/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1380[78];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1380[78] __attribute__((aligned(8))) = "You can select the original machine as you purchase the F-ZERO LICENSE CARD. ";
#pragma explicit_zero_data reset
