/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/sel/data/lbl_10_rodata_58.h"
#include "rel/sel/data/lbl_10_rodata_90.h"

extern const u32 lbl_10_rodata_0[12];
extern const u32 lbl_10_rodata_30[6];
extern const f64 lbl_10_rodata_48;
extern const f64 lbl_10_rodata_50;
#include "rel/sel/data/lbl_10_rodata_58.h"
#include "rel/sel/data/lbl_10_rodata_90.h"



#pragma explicit_zero_data on
__declspec(section ".rodata") const u32 lbl_10_rodata_0[12] __attribute__((aligned(8))) = {
    0x00000000U, 0x00000000U, 0x43A00000U, 0x43700000U, 0x3727C5ACU, 0x38D1B717U, 0x3F000000U, 0x43F00000U, 0x40000000U, 0x00000000U, 0x43300000U, 0x00000000U
};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const u32 lbl_10_rodata_30[6] __attribute__((aligned(8))) = {
    0x80000000U, 0x80000000U, 0x40000000U, 0x20000000U, 0x20000000U, 0x00000000U
};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const f64 lbl_10_rodata_48 __attribute__((aligned(8))) = 90.0;
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const f64 lbl_10_rodata_50 __attribute__((aligned(8))) = 4503601774854144.0;
#pragma explicit_zero_data reset


extern char lbl_10_data_6F0[];
#pragma explicit_zero_data on
__declspec(section ".rodata") const Data_lbl_10_rodata_58 lbl_10_rodata_58 __attribute__((aligned(8))) = {
    0x00000000U,
    0x00000025U,
    0x00000026U,
    0x00000027U,
    0x00000028U,
    0x00000029U,
    0x0000002AU,
    0x0000002BU,
    0x0000002CU,
    0x0000002DU,
    (u8 *)&lbl_10_data_6F0,
    (u8 *)&lbl_10_data_6F0,
    0x403E0000U,
    0x00000000U
};
#pragma explicit_zero_data reset


extern char lbl_10_data_6F0[];
#pragma explicit_zero_data on
__declspec(section ".rodata") const Data_lbl_10_rodata_90 lbl_10_rodata_90 __attribute__((aligned(8))) = {
    (u8 *)&lbl_10_data_6F0
};
#pragma explicit_zero_data reset
