/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1490[30];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1490[30] __attribute__((aligned(8))) = "Fastest Ghost by each Machine";
#pragma explicit_zero_data reset
