/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_4A68[74];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4A68[74] __attribute__((aligned(8))) = "Please insert the Memory Card\nbefore you insert the F-ZERO LICENSE CARD.\n";
#pragma explicit_zero_data reset
