/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern const f32 lbl_10_rodata_158[19];
extern const f32 lbl_10_rodata_1A4[15];
extern const f64 lbl_10_rodata_1E0;



#pragma explicit_zero_data on
__declspec(section ".rodata") const f32 lbl_10_rodata_158[19] __attribute__((aligned(4))) = {
    0.0f, 6.49305656e-41f, 6.5289298e-41f, 6.20607064e-41f, 6.42131008e-41f, 6.60067629e-41f, 6.38543684e-41f, 6.3495636e-41f, 6.24194388e-41f, 6.45718332e-41f, 6.63654953e-41f, 6.31369036e-41f, 6.27781712e-41f, 6.56480305e-41f, 0.0f, 0.0f, 2.21269722e-38f, 1.0f, 0.5f
};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const f32 lbl_10_rodata_1A4[15] __attribute__((aligned(4))) = {
    0.0f, 0.200000003f, 0.400000006f, 320.0f, 3.0f, 323.0f, 4.0f, 5.0f, 6.0f, 0.25f, 16384.0f, 65536.0f, 60.0f, 1.875f, 0.555555582f
};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const f64 lbl_10_rodata_1E0 __attribute__((aligned(8))) = 4503601774854144.0;
#pragma explicit_zero_data reset
