/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/sel/data/lbl_10_rodata_1C40.h"

extern const f64 lbl_10_rodata_1C38;
#include "rel/sel/data/lbl_10_rodata_1C40.h"
extern const u32 lbl_10_rodata_1CA0;



#pragma explicit_zero_data on
__declspec(section ".rodata") const f64 lbl_10_rodata_1C38 __attribute__((aligned(8))) = 4503601774854144.0;
#pragma explicit_zero_data reset


/* Preserve non-finite payloads and signed zero without compiler canonicalization. */
#pragma explicit_zero_data on
__declspec(section ".rodata") const Data_lbl_10_rodata_1C40 lbl_10_rodata_1C40 __attribute__((aligned(8))) = {{
    0x4330000000000000ULL, 0x4200000041C00000ULL, 0x41900000FFFFFF00ULL, 0x00FFFF0000FFFF00ULL, 0x00FFFF00000000FFULL, 0xFFFFFFFF41400000ULL, 0x0000000000000000ULL, 0x3FC999999999999AULL, 0x4028000000000000ULL, 0x4121999A00000000ULL, 0x4038000000000000ULL, 0x3F80000041200000ULL
}};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const u32 lbl_10_rodata_1CA0 __attribute__((aligned(8))) = 0x00FFFF00U;
#pragma explicit_zero_data reset
