/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1888[56];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1888[56] __attribute__((aligned(8))) = "You can join the Internet Ranking with your password. \n";
#pragma explicit_zero_data reset
