/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_4F88[44];
extern char lbl_10_data_4FB4[22];
extern char lbl_10_data_4FCC[22];
extern char lbl_10_data_4FE4[22];
extern char lbl_10_data_4FFC[22];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4F88[44] __attribute__((aligned(8))) = "If you don't have the F-ZERO LICENSE CARD. ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4FB4[22] __attribute__((aligned(4))) = "DONT_HAVE_LICENSE GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4FCC[22] __attribute__((aligned(4))) = "DONT_HAVE_LICENSE FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4FE4[22] __attribute__((aligned(4))) = "DONT_HAVE_LICENSE SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4FFC[22] __attribute__((aligned(4))) = "DONT_HAVE_LICENSE ITA";
#pragma explicit_zero_data reset
