/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1158[40];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1158[40] __attribute__((aligned(8))) = "Press start.  Waiting for challengers. ";
#pragma explicit_zero_data reset
