/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1290[22];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1290[22] __attribute__((aligned(8))) = "Select Your Machine. ";
#pragma explicit_zero_data reset
