/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_17A0[100];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_17A0[100] __attribute__((aligned(8))) = "Compete by yourself for the Best Total of certain laps. \n\tSelect either solo or against the gh"
    "ost.\n";
#pragma explicit_zero_data reset
