/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_6B88[3];
extern char lbl_10_data_6B8C[7];
extern char lbl_10_data_6B94[7];
extern char lbl_10_data_6B9C[7];
extern char lbl_10_data_6BA4[7];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6B88[3] __attribute__((aligned(8))) = "NO";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6B8C[7] __attribute__((aligned(4))) = "GER NO";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6B94[7] __attribute__((aligned(4))) = "FRE NO";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6B9C[7] __attribute__((aligned(4))) = "SPA NO";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6BA4[7] __attribute__((aligned(4))) = "ITA NO";
#pragma explicit_zero_data reset
