/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_5EE0[29];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5EE0[29] __attribute__((aligned(8))) = "Now receiving players' data.";
#pragma explicit_zero_data reset
