/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_D00[4];
extern char lbl_10_data_D04[12];
extern char lbl_10_data_D10[12];
extern char lbl_10_data_D1C[11];
extern char lbl_10_data_D28[11];
extern char lbl_10_data_D34[5];
extern char lbl_10_data_D3C[5];
extern char lbl_10_data_D44[8];
extern char lbl_10_data_D4C[6];
extern char lbl_10_data_D54[11];
extern char lbl_10_data_D60[14];
extern char lbl_10_data_D70[15];
extern char lbl_10_data_D80[7];
extern char lbl_10_data_D88[5];
extern char lbl_10_data_D90[11];
extern char lbl_10_data_D9C[11];
extern char lbl_10_data_DA8[14];
extern char lbl_10_data_DB8[6];
extern char lbl_10_data_DC0[9];
extern char lbl_10_data_DCC[12];
extern char lbl_10_data_DD8[15];
extern char lbl_10_data_DE8[7];
extern char lbl_10_data_DF0[10];
extern char lbl_10_data_DFC[12];
extern char lbl_10_data_E08[15];
extern char lbl_10_data_E18[8];
extern char lbl_10_data_E20[11];
extern char lbl_10_data_E2C[7];
extern char lbl_10_data_E34[10];
extern char lbl_10_data_E40[14];
extern char lbl_10_data_E50[9];
extern char lbl_10_data_E5C[11];
extern char lbl_10_data_E68[8];
extern char lbl_10_data_E70[18];
extern char lbl_10_data_E84[13];
extern char lbl_10_data_E94[15];
extern char lbl_10_data_EA4[10];
extern char lbl_10_data_EB0[11];
extern char lbl_10_data_EBC[14];
extern char lbl_10_data_ECC[8];
extern char lbl_10_data_ED4[12];
extern char lbl_10_data_EE0[7];
extern char lbl_10_data_EE8[5];
extern char lbl_10_data_EF0[6];
extern char lbl_10_data_EF8[6];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D00[4] __attribute__((aligned(8))) = "NON";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D04[12] __attribute__((aligned(4))) = "MASTER RECV";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D10[12] __attribute__((aligned(8))) = "MASTER SEND";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D1C[11] __attribute__((aligned(4))) = "SLAVE SEND";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D28[11] __attribute__((aligned(8))) = "SLAVE RECV";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D34[5] __attribute__((aligned(4))) = "INIT";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D3C[5] __attribute__((aligned(4))) = "TEST";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D44[8] __attribute__((aligned(4))) = "TESTEND";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D4C[6] __attribute__((aligned(4))) = "SETUP";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D54[11] __attribute__((aligned(4))) = "SETUP_DONE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D60[14] __attribute__((aligned(8))) = "SETUP_COUNTER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D70[15] __attribute__((aligned(8))) = "SETUP_CNT_DONE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D80[7] __attribute__((aligned(8))) = "UNLINK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D88[5] __attribute__((aligned(8))) = "COIN";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D90[11] __attribute__((aligned(8))) = "ENTRY_WAIT";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_D9C[11] __attribute__((aligned(4))) = "CHALLENGER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DA8[14] __attribute__((aligned(8))) = "CHALLENGER_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DB8[6] __attribute__((aligned(8))) = "ENTRY";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DC0[9] __attribute__((aligned(8))) = "ENTRY_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DCC[12] __attribute__((aligned(4))) = "SINGLECHECK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DD8[15] __attribute__((aligned(8))) = "SINGLECHECK_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DE8[7] __attribute__((aligned(8))) = "COURSE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DF0[10] __attribute__((aligned(8))) = "COURSE_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_DFC[12] __attribute__((aligned(4))) = "COURSE_DATA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E08[15] __attribute__((aligned(8))) = "COURSE_DATA_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E18[8] __attribute__((aligned(8))) = "MACHINE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E20[11] __attribute__((aligned(8))) = "MACHINE_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E2C[7] __attribute__((aligned(4))) = "CONFIG";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E34[10] __attribute__((aligned(4))) = "CONFIG_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E40[14] __attribute__((aligned(8))) = "COUNTERADJUST";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E50[9] __attribute__((aligned(8))) = "LINKWAIT";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E5C[11] __attribute__((aligned(4))) = "LINKWAITOK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E68[8] __attribute__((aligned(8))) = "LINKSEL";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E70[18] __attribute__((aligned(8))) = "LINKDELIVERYSTART";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E84[13] __attribute__((aligned(4))) = "LINKDELIVERY";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_E94[15] __attribute__((aligned(4))) = "LINKDELIVERYOK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EA4[10] __attribute__((aligned(4))) = "LINKSELOK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EB0[11] __attribute__((aligned(8))) = "COURSEVIEW";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EBC[14] __attribute__((aligned(4))) = "COURSEVIEW_OK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_ECC[8] __attribute__((aligned(4))) = "LINKREQ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_ED4[12] __attribute__((aligned(4))) = "LINKSTANDBY";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EE0[7] __attribute__((aligned(8))) = "LINKOK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EE8[5] __attribute__((aligned(8))) = "LINK";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EF0[6] __attribute__((aligned(8))) = "PAUSE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_EF8[6] __attribute__((aligned(8))) = "ERROR";
#pragma explicit_zero_data reset
