/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_6238[34];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6238[34] __attribute__((aligned(8))) = "Number of Rivals You've Destroyed";
#pragma explicit_zero_data reset
