/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_11B8[19];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_11B8[19] __attribute__((aligned(8))) = "Select Game Mode. ";
#pragma explicit_zero_data reset
