/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_64F0[2];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_64F0[2] __attribute__((aligned(8))) = "%";
#pragma explicit_zero_data reset
