/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_21B0[10];
extern char lbl_10_data_21BC[10];
extern char lbl_10_data_21C8[12];
extern char lbl_10_data_21D4[10];
extern char lbl_10_data_21E0[10];
extern char lbl_10_data_21EC[12];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_21B0[10] __attribute__((aligned(8))) = "MUTE CITY";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_21BC[10] __attribute__((aligned(4))) = "AEROPOLIS";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_21C8[12] __attribute__((aligned(8))) = "OUTER SPACE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_21D4[10] __attribute__((aligned(4))) = "PORT TOWN";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_21E0[10] __attribute__((aligned(8))) = "LIGHTNING";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_21EC[12] __attribute__((aligned(4))) = "GREEN PLANT";
#pragma explicit_zero_data reset
