/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_11E8[15];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_11E8[15] __attribute__((aligned(8))) = "Select a Cup. ";
#pragma explicit_zero_data reset
