/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2490[10];
extern char lbl_10_data_249C[14];
extern char lbl_10_data_24AC[14];
extern char lbl_10_data_24BC[14];
extern char lbl_10_data_24CC[14];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2490[10] __attribute__((aligned(8))) = "Customize";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_249C[14] __attribute__((aligned(4))) = "Customize GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_24AC[14] __attribute__((aligned(4))) = "Customize FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_24BC[14] __attribute__((aligned(4))) = "Customize SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_24CC[14] __attribute__((aligned(4))) = "Customize ITA";
#pragma explicit_zero_data reset
