/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2B50[3];
extern char lbl_10_data_2B54[7];
extern char lbl_10_data_2B5C[7];
extern char lbl_10_data_2B64[7];
extern char lbl_10_data_2B6C[7];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2B50[3] __attribute__((aligned(8))) = "Ac";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2B54[7] __attribute__((aligned(4))) = "Ac GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2B5C[7] __attribute__((aligned(4))) = "Ac FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2B64[7] __attribute__((aligned(4))) = "Ac SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2B6C[7] __attribute__((aligned(4))) = "Ac ITA";
#pragma explicit_zero_data reset
