/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_5038[42];
extern char lbl_10_data_5064[16];
extern char lbl_10_data_5074[16];
extern char lbl_10_data_5084[16];
extern char lbl_10_data_5094[16];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5038[42] __attribute__((aligned(8))) = "Failed to load. \nPlease remove the card. ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5064[16] __attribute__((aligned(4))) = "FAILED_LOAD GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5074[16] __attribute__((aligned(4))) = "FAILED_LOAD FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5084[16] __attribute__((aligned(4))) = "FAILED_LOAD SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5094[16] __attribute__((aligned(4))) = "FAILED_LOAD ITA";
#pragma explicit_zero_data reset
