/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern const char lbl_10_rodata_1AE8[16];



#pragma explicit_zero_data on
__declspec(section ".rodata") const char lbl_10_rodata_1AE8[16] __attribute__((aligned(8))) = "Capital Letters";
#pragma explicit_zero_data reset
