/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2288[12];
extern char lbl_10_data_2294[16];
extern char lbl_10_data_22A4[16];
extern char lbl_10_data_22B4[16];
extern char lbl_10_data_22C4[16];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2288[12] __attribute__((aligned(8))) = "Mode Select";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2294[16] __attribute__((aligned(4))) = "Mode Select GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_22A4[16] __attribute__((aligned(4))) = "Mode Select FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_22B4[16] __attribute__((aligned(4))) = "Mode Select SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_22C4[16] __attribute__((aligned(4))) = "Mode Select ITA";
#pragma explicit_zero_data reset
