/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_19B8[6];
extern char lbl_10_data_19C0[37];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_19B8[6] __attribute__((aligned(8))) = "EMPTY";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_19C0[37] __attribute__((aligned(8))) = "Two or more Controllers are needed. ";
#pragma explicit_zero_data reset
