/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_6380[14];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6380[14] __attribute__((aligned(8))) = "Participating";
#pragma explicit_zero_data reset
