/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_54E8[10];
extern char lbl_10_data_54F4[13];
extern char lbl_10_data_5504[13];
extern char lbl_10_data_5514[13];
extern char lbl_10_data_5524[13];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_54E8[10] __attribute__((aligned(8))) = "Proceed. ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_54F4[13] __attribute__((aligned(4))) = "PROCEED\t GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5504[13] __attribute__((aligned(4))) = "PROCEED\t FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5514[13] __attribute__((aligned(4))) = "PROCEED\t SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_5524[13] __attribute__((aligned(4))) = "PROCEED\t ITA";
#pragma explicit_zero_data reset
