/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1C70[33];
extern char lbl_10_data_1C94[37];
extern char lbl_10_data_1CBC[37];
extern char lbl_10_data_1CE4[37];
extern char lbl_10_data_1D0C[37];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1C70[33] __attribute__((aligned(8))) = "You haven't beaten the set time.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1C94[37] __attribute__((aligned(4))) = "GER You haven't beaten the set time.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1CBC[37] __attribute__((aligned(4))) = "FRE You haven't beaten the set time.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1CE4[37] __attribute__((aligned(4))) = "SPA You haven't beaten the set time.";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1D0C[37] __attribute__((aligned(4))) = "ITA You haven't beaten the set time.";
#pragma explicit_zero_data reset
