/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2648[11];
extern char lbl_10_data_2654[15];
extern char lbl_10_data_2664[15];
extern char lbl_10_data_2674[15];
extern char lbl_10_data_2684[15];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2648[11] __attribute__((aligned(8))) = "%d Players";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2654[15] __attribute__((aligned(4))) = "%d Players GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2664[15] __attribute__((aligned(4))) = "%d Players FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2674[15] __attribute__((aligned(4))) = "%d Players SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2684[15] __attribute__((aligned(4))) = "%d Players ITA";
#pragma explicit_zero_data reset
