/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2818[9];
extern char lbl_10_data_2824[13];
extern char lbl_10_data_2834[13];
extern char lbl_10_data_2844[13];
extern char lbl_10_data_2854[13];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2818[9] __attribute__((aligned(8))) = "Gachinko";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2824[13] __attribute__((aligned(4))) = "Gachinko GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2834[13] __attribute__((aligned(4))) = "Gachinko FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2844[13] __attribute__((aligned(4))) = "Gachinko SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2854[13] __attribute__((aligned(4))) = "Gachinko ITA";
#pragma explicit_zero_data reset
