/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_3148[51];
extern char lbl_10_data_317C[16];
extern char lbl_10_data_318C[16];
extern char lbl_10_data_319C[16];
extern char lbl_10_data_31AC[16];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_3148[51] __attribute__((aligned(8))) = "Failed to load. \n\tPlease remove the Memory Card. \n";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_317C[16] __attribute__((aligned(4))) = "Load Failed GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_318C[16] __attribute__((aligned(4))) = "Load Failed FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_319C[16] __attribute__((aligned(4))) = "Load Failed SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_31AC[16] __attribute__((aligned(4))) = "Load Failed ITA";
#pragma explicit_zero_data reset
