/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_23F0[9];
extern char lbl_10_data_23FC[13];
extern char lbl_10_data_240C[13];
extern char lbl_10_data_241C[13];
extern char lbl_10_data_242C[13];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_23F0[9] __attribute__((aligned(8))) = "Practice";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_23FC[13] __attribute__((aligned(4))) = "Practice GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_240C[13] __attribute__((aligned(4))) = "Practice FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_241C[13] __attribute__((aligned(4))) = "Practice SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_242C[13] __attribute__((aligned(4))) = "Practice ITA";
#pragma explicit_zero_data reset
