/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_2730[9];
extern char lbl_10_data_273C[13];
extern char lbl_10_data_274C[13];
extern char lbl_10_data_275C[13];
extern char lbl_10_data_276C[13];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_2730[9] __attribute__((aligned(8))) = "Standard";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_273C[13] __attribute__((aligned(4))) = "Standard GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_274C[13] __attribute__((aligned(4))) = "Standard FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_275C[13] __attribute__((aligned(4))) = "Standard SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_276C[13] __attribute__((aligned(4))) = "Standard ITA";
#pragma explicit_zero_data reset
