/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_6490[5];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6490[5] __attribute__((aligned(8))) = "Time";
#pragma explicit_zero_data reset
