/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1908[78];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1908[78] __attribute__((aligned(8))) = "VS BATTLE\nNo computers. \n\tSingle play will be a normal race with computers. \n";
#pragma explicit_zero_data reset
