/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_4040[74];
extern char lbl_10_data_408C[21];
extern char lbl_10_data_40A4[21];
extern char lbl_10_data_40BC[21];
extern char lbl_10_data_40D4[21];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_4040[74] __attribute__((aligned(8))) = "Now checking. \nDo not pull out the Memory Card. \nIt can damage the file\n ";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_408C[21] __attribute__((aligned(4))) = "Memcard checking GER";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_40A4[21] __attribute__((aligned(4))) = "Memcard checking FRA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_40BC[21] __attribute__((aligned(4))) = "Memcard checking SPA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_40D4[21] __attribute__((aligned(4))) = "Memcard checking ITA";
#pragma explicit_zero_data reset
