/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_6168[11];
extern char lbl_10_data_6174[7];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6168[11] __attribute__((aligned(8))) = "Played for";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6174[7] __attribute__((aligned(4))) = "%dTime";
#pragma explicit_zero_data reset
