/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/sel/data/lbl_10_data_538.h"

#include "rel/sel/data/lbl_10_data_538.h"


extern u8 lbl_10_data_460[];
extern u8 lbl_10_data_490[];
extern u8 lbl_10_data_4C0[];
extern u8 lbl_10_data_4F0[];
extern u8 lbl_10_data_514[];
#pragma explicit_zero_data on
__declspec(section ".data") Data_lbl_10_data_538 lbl_10_data_538 __attribute__((aligned(8))) = {
    (u8 *)&lbl_10_data_460,
    (u8 *)&lbl_10_data_490,
    (u8 *)&lbl_10_data_4C0,
    (u8 *)&lbl_10_data_4F0,
    (u8 *)&lbl_10_data_514
};
#pragma explicit_zero_data reset
