/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_63E8[10];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_63E8[10] __attribute__((aligned(8))) = "1st Place";
#pragma explicit_zero_data reset
