/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_6BD0[9];
extern char lbl_10_data_6BDC[19];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6BD0[9] __attribute__((aligned(8))) = "record.c";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_6BDC[19] __attribute__((aligned(4))) = "OKASII by tokieda\n";
#pragma explicit_zero_data reset
