/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_10_data_1D98[6];
extern char lbl_10_data_1DA0[10];
extern char lbl_10_data_1DAC[10];
extern char lbl_10_data_1DB8[10];
extern char lbl_10_data_1DC4[10];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1D98[6] __attribute__((aligned(8))) = "Pilot";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1DA0[10] __attribute__((aligned(8))) = "GER Pilot";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1DAC[10] __attribute__((aligned(4))) = "FRE Pilot";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1DB8[10] __attribute__((aligned(8))) = "SPA Pilot";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_10_data_1DC4[10] __attribute__((aligned(4))) = "ITA Pilot";
#pragma explicit_zero_data reset
