#ifndef REL_MAIN_REL_FONT_H
#define REL_MAIN_REL_FONT_H

#include "types.h"
#include "rel/main_rel/globals.h"

// Generated by `fzgx headers --module main_rel --tu font.c`: globals of font.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_1_bss_6C7CC: .bss size 0x10, 11 refs from font.c
typedef struct {
    u32 unk_0;  // 16 loads, 3 stores
    u8 pad_4[0xC];
} Obj_1_bss_6C7CC;
extern Obj_1_bss_6C7CC lbl_1_bss_6C7CC;

// lbl_1_bss_4E6A8: .bss size 0x4, 9 refs from font.c
extern u32 lbl_1_bss_4E6A8;

// lbl_1_bss_4E6AC: .bss size 0x4, 8 refs from font.c
extern u32 lbl_1_bss_4E6AC;

// lbl_1_data_1AEA8: .data size 0x9A0, 8 refs from font.c
typedef struct {
    u32 unk_0;  // 16 loads, 0 stores
    u8 unk_4;  // 3 loads, 0 stores
    u8 unk_5;  // 5 loads, 0 stores
    u8 pad_6[0x2];
    u32 unk_8;  // 2 loads, 0 stores
    u32 unk_C;  // 2 loads, 0 stores
    u8 unk_10;  // 2 loads, 0 stores
    u8 unk_11;  // 1 loads, 0 stores
    u8 pad_12[0x2];
    f32 unk_14;  // 1 loads, 0 stores
    f32 unk_18;  // 1 loads, 0 stores
    u8 pad_1C[0x10];
    u32 unk_2C;  // 10 loads, 0 stores
    u32 unk_30;  // 11 loads, 0 stores
    f32 unk_34;  // 6 loads, 0 stores
    u8 pad_38[0x968];
} Obj_1_data_1AEA8;
extern Obj_1_data_1AEA8 lbl_1_data_1AEA8;

// lbl_1_bss_6C7A0: .bss size 0x4, 6 refs from font.c
extern f32 lbl_1_bss_6C7A0;

// lbl_1_bss_4C678: .bss size 0x8, 6 refs from font.c
extern u32 lbl_1_bss_4C678;

// lbl_1_bss_646D2: .bss size 0xE, 5 refs from font.c
typedef struct {
    u16 unk_0;  // 7 loads, 4 stores
    u8 pad_2[0xC];
} Obj_1_bss_646D2;
extern Obj_1_bss_646D2 lbl_1_bss_646D2;

// lbl_1_data_1A3B8: .data size 0xAD8, 5 refs from font.c
typedef struct {
    u16 unk_0;  // 2 loads, 0 stores
    u8 pad_2[0xAD6];
} Obj_1_data_1A3B8;
extern Obj_1_data_1A3B8 lbl_1_data_1A3B8;

// lbl_1_bss_3E058: .bss size 0x4, 5 refs from font.c
extern u32 lbl_1_bss_3E058;

// lbl_1_data_FCD4: .data size 0x1D60, 5 refs from font.c
typedef struct {
    u8 pad_0[0x4];
    u32 unk_4;  // 3 loads, 0 stores
    u8 pad_8[0x4];
    u32 unk_C;  // 6 loads, 0 stores
} Obj_1_data_FCD4_At20;
typedef struct {
    u32 unk_0;  // 14 loads, 2 stores
    u32 unk_4;  // 2 loads, 0 stores
    u8 pad_8[0x18];
    Obj_1_data_FCD4_At20 *unk_20;  // 10 loads, 0 stores
    u8 unk_24;  // 13 loads, 0 stores
    u8 pad_25[0x1D3B];
} Obj_1_data_FCD4;
extern Obj_1_data_FCD4 lbl_1_data_FCD4;

// lbl_1_bss_4BA30: .bss size 0x14, 5 refs from font.c
typedef struct {
    u32 unk_0;  // 2 loads, 5 stores
    f32 unk_4;  // 1 loads, 1 stores
    f32 unk_8;  // 3 loads, 1 stores
    f32 unk_C;  // 3 loads, 1 stores
    f32 unk_10;  // 3 loads, 1 stores
} Obj_1_bss_4BA30;
extern Obj_1_bss_4BA30 lbl_1_bss_4BA30;

// lbl_1_data_1C504: .data size 0x4, 4 refs from font.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x2C];
    u32 unk_30;  // 5 loads, 2 stores
    f32 unk_34;  // 0 loads, 1 stores
    u8 pad_38[0x8];
    u32 unk_40;  // 2 loads, 1 stores
    u16 unk_44;  // 3 loads, 1 stores
    u16 unk_46;  // 3 loads, 1 stores
    u32 unk_48;  // 2 loads, 1 stores
} Obj_1_data_1C504_Target;
extern Obj_1_data_1C504_Target *lbl_1_data_1C504;

// lbl_1_bss_3E05C: .bss size 0x4, 4 refs from font.c
extern f32 lbl_1_bss_3E05C;

// lbl_1_bss_4BB30: .bss size 0xC, 3 refs from font.c
typedef struct {
    u8 unk_0;  // 17 loads, 5 stores
    u8 unk_1;  // 2 loads, 2 stores
    u8 unk_2;  // 2 loads, 2 stores
    u8 unk_3;  // 3 loads, 3 stores
    u8 unk_4;  // 7 loads, 7 stores
    u8 pad_5[0x3];
    u32 unk_8;  // 15 loads, 11 stores
} Obj_1_bss_4BB30;
extern Obj_1_bss_4BB30 lbl_1_bss_4BB30;

// lbl_1_bss_40BBC: .bss size 0xB0, 3 refs from font.c
typedef struct {
    u32 unk_0;  // 2 loads, 3 stores
    u32 unk_4;  // 0 loads, 1 stores
    u8 pad_8[0xA8];
} Obj_1_bss_40BBC;
extern Obj_1_bss_40BBC lbl_1_bss_40BBC;

// lbl_1_bss_4BA44: .bss size 0x14, 3 refs from font.c
typedef struct {
    u32 unk_0;  // 1 loads, 1 stores
    f32 unk_4;  // 1 loads, 1 stores
    f32 unk_8;  // 2 loads, 1 stores
    f32 unk_C;  // 2 loads, 1 stores
    f32 unk_10;  // 2 loads, 1 stores
} Obj_1_bss_4BA44;
extern Obj_1_bss_4BA44 lbl_1_bss_4BA44;

// lbl_1_data_1C500: .data size 0x4, 2 refs from font.c (own data block)
extern u32 lbl_1_data_1C500;

// lbl_1_bss_4C684: .bss size 0x4, 2 refs from font.c
extern u32 lbl_1_bss_4C684;

// lbl_1_bss_4BA5C: .bss size 0x4, 2 refs from font.c
extern u32 lbl_1_bss_4BA5C;

// lbl_1_bss_4BA60: .bss size 0x20, 2 refs from font.c
extern u8 lbl_1_bss_4BA60[0x20];

// lbl_1_bss_4BA58: .bss size 0x4, 2 refs from font.c
extern u32 lbl_1_bss_4BA58;

// lbl_1_bss_6C710: .bss size 0x88, 2 refs from font.c
extern u8 lbl_1_bss_6C710[0x88];

// lbl_1_bss_4E6B0: .bss size 0x20, 2 refs from font.c
extern u8 lbl_1_bss_4E6B0[0x20];

// lbl_1_bss_4BB40: .bss size 0x5C, 2 refs from font.c
typedef struct {
    u32 unk_0;  // 2 loads, 2 stores
    u32 unk_4;  // 1 loads, 1 stores
    u8 pad_8[0x54];
} Obj_1_bss_4BB40;
extern Obj_1_bss_4BB40 lbl_1_bss_4BB40;

// lbl_1_bss_4BB3C: .bss size 0x1, 2 refs from font.c
extern u8 lbl_1_bss_4BB3C;

// lbl_1_bss_3F60C: .bss size 0x15B0, 2 refs from font.c
extern u8 lbl_1_bss_3F60C[0x15B0];

// lbl_1_bss_4C680: .bss size 0x4, 2 refs from font.c
extern u32 lbl_1_bss_4C680;

// lbl_1_bss_646E0: .bss size 0x4, 2 refs from font.c
extern u32 lbl_1_bss_646E0;

// lbl_1_bss_646E4: .bss size 0x4, 2 refs from font.c
extern u32 lbl_1_bss_646E4;

// lbl_1_data_1C508: .data size 0x70, 2 refs from font.c (own data block)
typedef struct {
    f32 unk_0;  // 1 loads, 1 stores
    u8 pad_4[0x6C];
} Obj_1_data_1C508;
extern Obj_1_data_1C508 lbl_1_data_1C508;

// jumptable_1_data_1BFD8: .data size 0xDC, 1 refs from font.c (own data block)
extern u8 jumptable_1_data_1BFD8[0xDC];

// jumptable_1_data_1C304: .data size 0x98, 1 refs from font.c (own data block)
extern u8 jumptable_1_data_1C304[0x98];

// lbl_1_data_1C5DC: .data size 0x4, 1 refs from font.c (own data block)
extern u32 lbl_1_data_1C5DC;

// lbl_1_data_1C5EC: .data size 0x64, 1 refs from font.c (own data block)
extern u8 lbl_1_data_1C5EC[0x64];

// lbl_1_data_1BCC8: .data size 0xBC, 1 refs from font.c (own data block)
extern u8 lbl_1_data_1BCC8[0xBC];

// jumptable_1_data_1BEFC: .data size 0xDC, 1 refs from font.c (own data block)
extern u8 jumptable_1_data_1BEFC[0xDC];

// jumptable_1_data_1C578: .data size 0x5C, 1 refs from font.c (own data block)
extern u8 jumptable_1_data_1C578[0x5C];

// jumptable_1_data_1BD84: .data size 0x178, 1 refs from font.c (own data block)
extern u8 jumptable_1_data_1BD84[0x178];

#endif  // REL_MAIN_REL_FONT_H
