#ifndef REL_PILOTPOINT_GLOBALS_H
#define REL_PILOTPOINT_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module pilotpoint`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_14_bss_0: .bss size 0xC, referenced by 20 functions, shape {'object': 218}
typedef struct {
    u32 unk_0;  // 13 loads, 8 stores
    u32 unk_4;  // 2 loads, 2 stores
    u32 unk_8;  // 10 loads, 7 stores
} Obj_14_bss_0;
extern Obj_14_bss_0 lbl_14_bss_0;

#endif  // REL_PILOTPOINT_GLOBALS_H
