#ifndef REL_PILOTPOINT_PILOTPOINT_H
#define REL_PILOTPOINT_PILOTPOINT_H

#include "types.h"
#include "rel/pilotpoint/globals.h"

// Generated by `fzgx headers --module pilotpoint --tu pilotpoint.c`: globals of pilotpoint.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_14_bss_110: .bss size 0x50, 18 refs from pilotpoint.c
typedef struct {
    u32 unk_0;  // 6 loads, 4 stores
    s16 unk_4;  // 24 loads, 5 stores
    u8 pad_6[0x2];
    s16 unk_8;  // 11 loads, 0 stores
    u8 pad_A[0x2];
    u32 unk_C;  // 28 loads, 1 stores
    u8 pad_10[0x4];
    u32 unk_14;  // 1 loads, 0 stores
    u8 pad_18[0xC];
    u32 unk_24;  // 1 loads, 0 stores
    u8 pad_28[0xC];
    u32 unk_34;  // 1 loads, 0 stores
    u8 pad_38[0xC];
    u32 unk_44;  // 1 loads, 0 stores
    u32 unk_48;  // 3 loads, 4 stores
    u32 unk_4C;  // 3 loads, 1 stores
} Obj_14_bss_110;
extern Obj_14_bss_110 lbl_14_bss_110;

// lbl_14_data_0: .data size 0x4, 12 refs from pilotpoint.c
extern u32 lbl_14_data_0;

// lbl_14_bss_160: .bss size 0x20, 5 refs from pilotpoint.c
typedef struct {
    s16 unk_0;  // 7 loads, 0 stores
    u8 pad_2[0x1E];
} Obj_14_bss_160;
extern Obj_14_bss_160 lbl_14_bss_160;

// lbl_14_bss_20: .bss size 0xEC, 4 refs from pilotpoint.c
typedef struct {
    u32 unk_0;  // 4 loads, 0 stores
    u8 pad_4[0xE8];
} Obj_14_bss_20;
extern Obj_14_bss_20 lbl_14_bss_20;

// lbl_14_bss_92C4: .bss size 0x24, 4 refs from pilotpoint.c
typedef struct {
    u8 pad_0[0x4];
    f32 unk_4;  // 0 loads, 2 stores
    f32 unk_8;  // 0 loads, 2 stores
    f32 unk_C;  // 0 loads, 2 stores
    f32 unk_10;  // 0 loads, 4 stores
    f32 unk_14;  // 0 loads, 2 stores
    f32 unk_18;  // 0 loads, 2 stores
    u8 pad_1C[0x8];
} Obj_14_bss_92C4;
extern Obj_14_bss_92C4 lbl_14_bss_92C4;

// lbl_14_bss_8350: .bss size 0x4, 4 refs from pilotpoint.c
typedef struct {
    u8 pad_0[0x88];
    u32 unk_88;  // 2 loads, 0 stores
    u8 pad_8C[0x1C];
    f32 unk_A8;  // 0 loads, 4 stores
    f32 unk_AC;  // 0 loads, 4 stores
    f32 unk_B0;  // 0 loads, 4 stores
} Obj_14_bss_8350_Target;
extern Obj_14_bss_8350_Target *lbl_14_bss_8350;

// lbl_14_bss_92BC: .bss size 0x4, 4 refs from pilotpoint.c
extern u32 lbl_14_bss_92BC;

// lbl_14_bss_9460: .bss size 0x4, 3 refs from pilotpoint.c
extern u32 lbl_14_bss_9460;

// lbl_14_bss_180: .bss size 0x81C0, 3 refs from pilotpoint.c
extern u8 lbl_14_bss_180[0x81C0];

// lbl_14_bss_8354: .bss size 0xEA0, 3 refs from pilotpoint.c
extern u8 lbl_14_bss_8354[0xEA0];

// lbl_14_bss_8340: .bss size 0x4, 3 refs from pilotpoint.c
typedef struct {
    u8 pad_0[0x360];
    s16 unk_360;  // 4 loads, 0 stores
    u8 pad_362[0x35E];
    s16 unk_6C0;  // 4 loads, 0 stores
    u8 pad_6C2[0x35E];
} Obj_14_bss_8340_Target;
extern Obj_14_bss_8340_Target *lbl_14_bss_8340;  // array of 0xA20-byte records

// lbl_14_bss_92C0: .bss size 0x4, 3 refs from pilotpoint.c
extern u32 lbl_14_bss_92C0;

// lbl_14_bss_9452: .bss size 0x2, 2 refs from pilotpoint.c
extern s16 lbl_14_bss_9452;

// lbl_14_data_2F36: .data size 0x12, 2 refs from pilotpoint.c
typedef struct {
    s16 unk_0;  // 6 loads, 0 stores
    u8 pad_2[0x10];
} Obj_14_data_2F36;
extern Obj_14_data_2F36 lbl_14_data_2F36;

// lbl_14_bss_9464: .bss size 0x1E, 2 refs from pilotpoint.c
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 unk_1;  // 1 loads, 0 stores
    u16 unk_2;  // 1 loads, 0 stores
    u8 unk_4;  // 1 loads, 0 stores
    u8 pad_5[0x3];
    u8 unk_8;  // 1 loads, 0 stores
    u8 pad_9[0x15];
} Obj_14_bss_9464;
extern Obj_14_bss_9464 lbl_14_bss_9464;

// lbl_14_bss_92E8: .bss size 0x8, 2 refs from pilotpoint.c
typedef struct {
    s16 unk_0;  // 1 loads, 1 stores
    s16 unk_2;  // 1 loads, 1 stores
    s16 unk_4;  // 1 loads, 1 stores
    s16 unk_6;  // 1 loads, 1 stores
} Obj_14_bss_92E8;
extern Obj_14_bss_92E8 lbl_14_bss_92E8;

// lbl_14_bss_92F8: .bss size 0x4, 2 refs from pilotpoint.c
extern u32 lbl_14_bss_92F8;

// lbl_14_data_2FB0: .data size 0xD, 2 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_2FB0[0xD];

// lbl_14_data_300C: .data size 0x1C, 2 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_300C[0x1C];

// lbl_14_bss_92F0: .bss size 0x8, 2 refs from pilotpoint.c
typedef struct {
    s16 unk_0;  // 1 loads, 0 stores
    s16 unk_2;  // 1 loads, 0 stores
    s16 unk_4;  // 1 loads, 0 stores
    s16 unk_6;  // 1 loads, 0 stores
} Obj_14_bss_92F0;
extern Obj_14_bss_92F0 lbl_14_bss_92F0;

// lbl_14_data_3060: .data size 0x74, 2 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_3060[0x74];

// lbl_14_data_30D4: .data size 0x170, 1 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_30D4[0x170];

// lbl_14_data_3244: .data size 0x4, 1 refs from pilotpoint.c (own data block)
extern u32 lbl_14_data_3244;

// lbl_14_data_3028: .data size 0x7, 1 refs from pilotpoint.c (own data block)
extern u32 lbl_14_data_3028;

// lbl_14_data_3030: .data size 0x18, 1 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_3030[0x18];

// lbl_14_data_2FC0: .data size 0x4C, 1 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_2FC0[0x4C];

// lbl_14_data_3048: .data size 0x17, 1 refs from pilotpoint.c (own data block)
extern u8 lbl_14_data_3048[0x17];

// lbl_14_data_3248: .data size 0x3, 1 refs from pilotpoint.c (own data block)
extern u32 lbl_14_data_3248;

#endif  // REL_PILOTPOINT_PILOTPOINT_H
