/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/game.h"

extern u8 lbl_1_bss_5480[0x20700];



__declspec(section ".data") u8 lbl_1_bss_5480[0x20700] __attribute__((aligned(32)));
