/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/main_rel/game.h"

extern Obj_1_bss_6EAD0 lbl_1_bss_6EAD0;



__declspec(section ".data") Obj_1_bss_6EAD0 lbl_1_bss_6EAD0 __attribute__((aligned(16)));
