#ifndef REL_CUSTOMIZE_CUSTOMIZE_H
#define REL_CUSTOMIZE_CUSTOMIZE_H

#include "types.h"
#include "rel/customize/globals.h"

// Generated by `fzgx headers --module customize --tu customize.c`: globals of customize.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_3_bss_7ED58: .bss size 0x48, 8 refs from customize.c
typedef struct {
    u32 unk_0;  // 2 loads, 2 stores
    u8 unk_4;  // 0 loads, 2 stores
    u8 pad_5[0x3];
    u32 unk_8;  // 4 loads, 3 stores
    u32 unk_C;  // 1 loads, 3 stores
    u32 unk_10;  // 0 loads, 1 stores
    u8 unk_14;  // 1 loads, 0 stores
    u8 pad_15[0x33];
} Obj_3_bss_7ED58;
extern Obj_3_bss_7ED58 lbl_3_bss_7ED58;

// lbl_3_data_1A18: .data size 0x4, 6 refs from customize.c (own data block)
extern u32 lbl_3_data_1A18;

// lbl_3_bss_7EDA0: .bss size 0x20, 4 refs from customize.c
typedef struct {
    u32 unk_0;  // 2 loads, 2 stores
    u8 pad_4[0x1C];
} Obj_3_bss_7EDA0;
extern Obj_3_bss_7EDA0 lbl_3_bss_7EDA0;

// lbl_3_data_1A10: .data size 0x4, 3 refs from customize.c (own data block)
extern u32 lbl_3_data_1A10;

// lbl_3_bss_7EBA4: .bss size 0x4, 3 refs from customize.c
typedef struct {
    u8 pad_0[0x390];
    u32 unk_390;  // 0 loads, 2 stores
    u8 pad_394[0xC];
    u32 unk_3A0;  // 1 loads, 2 stores
    u32 unk_3A4;  // 1 loads, 2 stores
    u8 pad_3A8[0x12];
    u16 unk_3BA;  // 0 loads, 2 stores
} Obj_3_bss_7EBA4_Target;
extern Obj_3_bss_7EBA4_Target *lbl_3_bss_7EBA4;

// lbl_3_data_11DC: .data size 0x54, 3 refs from customize.c (own data block)
extern u8 lbl_3_data_11DC[0x54];

// lbl_3_bss_7EBA8: .bss size 0x4, 3 refs from customize.c
extern u32 lbl_3_bss_7EBA8;

// lbl_3_bss_A1784: .bss size 0x14, 2 refs from customize.c
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x10];
} Obj_3_bss_A1784;
extern Obj_3_bss_A1784 lbl_3_bss_A1784;

// lbl_3_bss_A179C: .bss size 0x4, 2 refs from customize.c
extern u32 lbl_3_bss_A179C;

// lbl_3_data_1A14: .data size 0x4, 2 refs from customize.c (own data block)
extern u32 lbl_3_data_1A14;

// lbl_3_data_1958: .data size 0x18, 2 refs from customize.c (own data block)
extern u8 lbl_3_data_1958[0x18];

// lbl_3_data_B8: .data size 0x4, 2 refs from customize.c
extern u32 lbl_3_data_B8;

// lbl_3_bss_2C584: .bss size 0x188, 2 refs from customize.c
typedef struct {
    s16 unk_0;  // 4 loads, 0 stores
    u8 pad_2[0x2];
    u32 unk_4;  // 6 loads, 1 stores
    u8 pad_8[0x180];
} Obj_3_bss_2C584;
extern Obj_3_bss_2C584 lbl_3_bss_2C584;

// lbl_3_bss_2C7C0: .bss size 0x41100, 2 refs from customize.c
typedef struct {
    u8 pad_0[0x390];
    u32 unk_390;  // 2 loads, 2 stores
    u8 pad_394[0xC];
    u32 unk_3A0;  // 0 loads, 2 stores
    u32 unk_3A4;  // 2 loads, 0 stores
} Obj_3_bss_2C7C0_At0;
typedef struct {
    Obj_3_bss_2C7C0_At0 *unk_0;  // 2 loads, 1 stores
    u8 unk_4;  // 0 loads, 1 stores
    u8 pad_5[0x7];
    u32 unk_C;  // 0 loads, 2 stores
    u8 pad_10[0x410F0];
} Obj_3_bss_2C7C0;
extern Obj_3_bss_2C7C0 lbl_3_bss_2C7C0;

// lbl_3_data_1A1C: .data size 0x11, 1 refs from customize.c (own data block)
extern u8 lbl_3_data_1A1C[0x11];

#endif  // REL_CUSTOMIZE_CUSTOMIZE_H
