#ifndef REL_CUSTOMIZE_EDITOR_H
#define REL_CUSTOMIZE_EDITOR_H

#include "types.h"
#include "rel/customize/globals.h"

// Generated by `fzgx headers --module customize --tu editor.c`: globals of editor.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_3_bss_A23EC: .bss size 0x1C, 9 refs from editor.c
typedef struct {
    u8 unk_0;  // 13 loads, 2 stores
    u8 pad_1[0x3];
    u32 unk_4;  // 2 loads, 1 stores
    u32 unk_8;  // 2 loads, 1 stores
    u32 unk_C;  // 7 loads, 6 stores
    u8 unk_10;  // 3 loads, 6 stores
    u8 unk_11;  // 10 loads, 3 stores
    u8 unk_12;  // 11 loads, 0 stores
    u8 pad_13[0x1];
    s16 unk_14;  // 3 loads, 2 stores
    u8 unk_16;  // 4 loads, 5 stores
    u8 unk_17;  // 1 loads, 0 stores
    u8 unk_18;  // 1 loads, 0 stores
    u8 pad_19[0x3];
} Obj_3_bss_A23EC;
extern Obj_3_bss_A23EC lbl_3_bss_A23EC;

// lbl_3_bss_A2410: .bss size 0x28, 6 refs from editor.c
typedef struct {
    u8 unk_0;  // 1 loads, 7 stores
    u8 unk_1;  // 1 loads, 1 stores
    u8 unk_2;  // 1 loads, 1 stores
    u8 pad_3[0x1];
    u8 unk_4;  // 1 loads, 3 stores
    u8 unk_5;  // 0 loads, 1 stores
    u8 unk_6;  // 0 loads, 1 stores
    u8 pad_7[0x1];
    u32 unk_8;  // 8 loads, 10 stores
    u8 unk_C;  // 24 loads, 9 stores
    u8 unk_D;  // 11 loads, 0 stores
    s16 unk_E;  // 1 loads, 1 stores
    u16 unk_10;  // 11 loads, 2 stores
    u16 unk_12;  // 10 loads, 2 stores
    u16 unk_14;  // 10 loads, 2 stores
    u16 unk_16;  // 0 loads, 1 stores
    s16 unk_18;  // 4 loads, 2 stores
    u8 pad_1A[0x2];
    f32 unk_1C;  // 3 loads, 8 stores
    s16 unk_20;  // 2 loads, 5 stores
    u8 pad_22[0x6];
} Obj_3_bss_A2410;
extern Obj_3_bss_A2410 lbl_3_bss_A2410;

// lbl_3_data_35C0: .data size 0x58, 3 refs from editor.c (own data block)
typedef struct {
    u8 pad_0[0x1];
    u8 unk_1;  // 1 loads, 0 stores
    u8 unk_2;  // 1 loads, 0 stores
    u8 pad_3[0x55];
} Obj_3_data_35C0;
extern Obj_3_data_35C0 lbl_3_data_35C0;

// lbl_3_bss_A2438: .bss size 0x1C, 2 refs from editor.c
typedef struct {
    u8 unk_0;  // 23 loads, 1 stores
    u8 pad_1[0x3];
    u32 unk_4;  // 3 loads, 14 stores
    u32 unk_8;  // 10 loads, 6 stores
    u8 unk_C;  // 13 loads, 2 stores
    u8 unk_D;  // 0 loads, 1 stores
    u8 unk_E;  // 1 loads, 13 stores
    u8 unk_F;  // 13 loads, 5 stores
    u8 unk_10;  // 14 loads, 14 stores
    u8 pad_11[0x1];
    s16 unk_12;  // 12 loads, 3 stores
    u8 unk_14;  // 9 loads, 3 stores
    u8 unk_15;  // 11 loads, 5 stores
    s16 unk_16;  // 3 loads, 2 stores
    s16 unk_18;  // 2 loads, 4 stores
    s16 unk_1A;  // 2 loads, 4 stores
} Obj_3_bss_A2438;
extern Obj_3_bss_A2438 lbl_3_bss_A2438;

// lbl_3_data_3738: .data size 0x48, 2 refs from editor.c (own data block)
typedef struct {
    u32 unk_0;  // 3 loads, 0 stores
    u8 pad_4[0xC];
    u32 unk_10;  // 1 loads, 0 stores
    u32 unk_14;  // 1 loads, 0 stores
    u8 pad_18[0x30];
} Obj_3_data_3738;
extern Obj_3_data_3738 lbl_3_data_3738;

// lbl_3_data_3618: .data size 0x120, 2 refs from editor.c (own data block)
typedef struct {
    u8 pad_0[0x4];
    u32 unk_4;  // 1 loads, 0 stores
    u32 unk_8;  // 1 loads, 0 stores
    u16 unk_C;  // 6 loads, 4 stores
    u8 pad_E[0x112];
} Obj_3_data_3618;
extern Obj_3_data_3618 lbl_3_data_3618;

// lbl_3_data_35B0: .data size 0x9, 2 refs from editor.c (own data block)
extern u8 lbl_3_data_35B0[0x9];

#endif  // REL_CUSTOMIZE_EDITOR_H
