#ifndef REL_CUSTOMIZE_EMB_PASTE_EDITOR_H
#define REL_CUSTOMIZE_EMB_PASTE_EDITOR_H

#include "types.h"
#include "rel/customize/globals.h"

// Generated by `fzgx headers --module customize --tu emb_paste_editor.c`: globals of emb_paste_editor.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_3_bss_7EDD8: .bss size 0x68, 12 refs from emb_paste_editor.c
typedef struct {
    u32 unk_0;  // 0 loads, 1 stores
    u32 unk_4;  // 2 loads, 1 stores
    u8 pad_8[0x2];
    s16 unk_A;  // 1 loads, 1 stores
    u32 unk_C;  // 14 loads, 8 stores
    u32 unk_10;  // 2 loads, 4 stores
    u8 unk_14;  // 23 loads, 0 stores
    u8 unk_15;  // 11 loads, 0 stores
    u8 pad_16[0x2];
    u32 unk_18;  // 6 loads, 6 stores
    s16 unk_1C;  // 4 loads, 0 stores
    u8 unk_1E;  // 9 loads, 3 stores
    u8 unk_1F;  // 9 loads, 2 stores
    u8 unk_20;  // 2 loads, 3 stores
    u8 unk_21;  // 2 loads, 3 stores
    s16 unk_22;  // 2 loads, 2 stores
    s16 unk_24;  // 13 loads, 5 stores
    s16 unk_26;  // 3 loads, 2 stores
    s16 unk_28;  // 2 loads, 2 stores
    u16 unk_2A;  // 1 loads, 0 stores
    u32 unk_2C;  // 0 loads, 3 stores
    u32 unk_30;  // 0 loads, 1 stores
    u32 unk_34;  // 0 loads, 1 stores
    u32 unk_38;  // 0 loads, 1 stores
    u8 unk_3C;  // 12 loads, 2 stores
    u8 pad_3D[0x9];
    u8 unk_46;  // 2 loads, 1 stores
    u8 unk_47;  // 0 loads, 1 stores
    s16 unk_48;  // 2 loads, 2 stores
    u8 pad_4A[0x2];
    s16 unk_4C;  // 2 loads, 2 stores
    s16 unk_4E;  // 2 loads, 2 stores
    u8 pad_50[0x1];
    u8 unk_51;  // 1 loads, 2 stores
    u8 pad_52[0x16];
} Obj_3_bss_7EDD8;
extern Obj_3_bss_7EDD8 lbl_3_bss_7EDD8;

// lbl_3_bss_7EDC0: .bss size 0xC, 7 refs from emb_paste_editor.c
typedef struct {
    u8 pad_0[0x5];
    u8 unk_5;  // 1 loads, 0 stores
    u8 pad_6[0x1];
    u8 unk_7;  // 0 loads, 1 stores
    u8 unk_8;  // 1 loads, 0 stores
} Obj_3_bss_7EDC0_At0;
typedef struct {
    Obj_3_bss_7EDC0_At0 *unk_0;  // 20 loads, 1 stores
    u8 pad_4[0x4];
    u32 unk_8;  // 4 loads, 2 stores
} Obj_3_bss_7EDC0;
extern Obj_3_bss_7EDC0 lbl_3_bss_7EDC0;

// lbl_3_bss_7EE40: .bss size 0x81C0, 7 refs from emb_paste_editor.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 pad_4[0x3];
    u8 unk_7;  // 0 loads, 5 stores
    u8 unk_8;  // 4 loads, 3 stores
    u8 pad_9[0x17];
    s16 unk_20;  // 1 loads, 0 stores
    u8 pad_22[0x2];
    u32 unk_24;  // 14 loads, 2 stores
    u32 unk_28;  // 1 loads, 0 stores
    u16 unk_2C;  // 1 loads, 0 stores
    u8 pad_2E[0x2];
    f32 unk_30;  // 0 loads, 1 stores
    f32 unk_34;  // 0 loads, 1 stores
    u8 pad_38[0x28];
    f32 unk_60;  // 0 loads, 1 stores
    f32 unk_64;  // 0 loads, 1 stores
    u8 pad_68[0x8158];
} Obj_3_bss_7EE40;
extern Obj_3_bss_7EE40 lbl_3_bss_7EE40;

// lbl_3_bss_87040: .bss size 0x81C0, 5 refs from emb_paste_editor.c
typedef struct {
    u8 pad_0[0x24];
    u32 unk_24;  // 1 loads, 1 stores
    u32 unk_28;  // 0 loads, 2 stores
    u16 unk_2C;  // 0 loads, 2 stores
    u8 pad_2E[0x17];
    u8 unk_45;  // 1 loads, 0 stores
    u8 pad_46[0x2];
    u32 unk_48;  // 0 loads, 2 stores
    u32 unk_4C;  // 0 loads, 2 stores
    u32 unk_50;  // 0 loads, 2 stores
    u32 unk_54;  // 0 loads, 2 stores
    u32 unk_58;  // 0 loads, 2 stores
    u32 unk_5C;  // 0 loads, 2 stores
    f32 unk_60;  // 1 loads, 2 stores
    f32 unk_64;  // 1 loads, 2 stores
    u8 pad_68[0x8158];
} Obj_3_bss_87040;
extern Obj_3_bss_87040 lbl_3_bss_87040;

// lbl_3_data_1A40: .data size 0x2, 3 refs from emb_paste_editor.c
extern u16 lbl_3_data_1A40;

// lbl_3_bss_A1768: .bss size 0x4, 3 refs from emb_paste_editor.c
extern u32 lbl_3_bss_A1768;

// lbl_3_bss_87000: .bss size 0x40, 2 refs from emb_paste_editor.c
typedef struct {
    u16 unk_0;  // 0 loads, 4 stores
    u8 pad_2[0x2];
    u32 unk_4;  // 4 loads, 0 stores
    u32 unk_8;  // 7 loads, 0 stores
    u8 pad_C[0x34];
} Obj_3_bss_87000;
extern Obj_3_bss_87000 lbl_3_bss_87000;

// lbl_3_data_32DC: .data size 0x13, 2 refs from emb_paste_editor.c (own data block)
extern u8 lbl_3_data_32DC[0x13];

// lbl_3_bss_9F640: .bss size 0x24, 2 refs from emb_paste_editor.c
typedef struct {
    u8 pad_0[0x4];
    f32 unk_4;  // 1 loads, 2 stores
    f32 unk_8;  // 1 loads, 2 stores
    f32 unk_C;  // 4 loads, 3 stores
    u32 unk_10;  // 1 loads, 1 stores
    u32 unk_14;  // 1 loads, 1 stores
    u32 unk_18;  // 1 loads, 1 stores
    u8 pad_1C[0x8];
} Obj_3_bss_9F640;
extern Obj_3_bss_9F640 lbl_3_bss_9F640;

// lbl_3_bss_9F690: .bss size 0x20D8, 2 refs from emb_paste_editor.c
typedef struct {
    u8 pad_0[0x4];
    f32 unk_4;  // 0 loads, 2 stores
    f32 unk_8;  // 0 loads, 2 stores
    f32 unk_C;  // 0 loads, 2 stores
    f32 unk_10;  // 0 loads, 1 stores
    f32 unk_14;  // 0 loads, 1 stores
    f32 unk_18;  // 1 loads, 1 stores
    u8 pad_1C[0x20BC];
} Obj_3_bss_9F690;
extern Obj_3_bss_9F690 lbl_3_bss_9F690;

// lbl_3_data_3360: .data size 0xC, 2 refs from emb_paste_editor.c (own data block)
extern u8 lbl_3_data_3360[0xC];

// lbl_3_data_32F0: .data size 0x1, 1 refs from emb_paste_editor.c (own data block)
extern u8 lbl_3_data_32F0;

#endif  // REL_CUSTOMIZE_EMB_PASTE_EDITOR_H
