#ifndef REL_CUSTOMIZE_EMBLEM_H
#define REL_CUSTOMIZE_EMBLEM_H

#include "types.h"
#include "rel/customize/globals.h"

// Generated by `fzgx headers --module customize --tu emblem.c`: globals of emblem.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_3_bss_A17A0: .bss size 0x2C, 10 refs from emblem.c
typedef struct {
    u32 unk_0;  // 5 loads, 3 stores
    u8 pad_4[0x4];
    u8 unk_8;  // 1 loads, 0 stores
    u8 unk_9;  // 1 loads, 0 stores
    u8 unk_A;  // 1 loads, 0 stores
    u8 unk_B;  // 1 loads, 0 stores
    u8 pad_C[0x4];
    s16 unk_10;  // 2 loads, 1 stores
    s16 unk_12;  // 2 loads, 1 stores
    s16 unk_14;  // 3 loads, 0 stores
    s16 unk_16;  // 4 loads, 3 stores
    s16 unk_18;  // 3 loads, 2 stores
    s16 unk_1A;  // 14 loads, 6 stores
    u8 unk_1C;  // 1 loads, 0 stores
    u8 pad_1D[0x3];
    u32 unk_20;  // 3 loads, 0 stores
    u8 pad_24[0x8];
} Obj_3_bss_A17A0;
extern Obj_3_bss_A17A0 lbl_3_bss_A17A0;

// lbl_3_bss_A23D8: .bss size 0x2, 7 refs from emblem.c
extern u16 lbl_3_bss_A23D8;

// lbl_3_bss_A23E0: .bss size 0x8, 5 refs from emblem.c
extern u32 lbl_3_bss_A23E0;

// lbl_3_data_3574: .data size 0x3C, 5 refs from emblem.c (own data block)
extern u8 lbl_3_data_3574[0x3C];

// lbl_3_bss_A17D4: .bss size 0xC04, 3 refs from emblem.c
typedef struct {
    u8 pad_0[0x4];
    u8 unk_4;  // 1 loads, 1 stores
    u8 pad_5[0x1];
    u8 unk_6;  // 2 loads, 1 stores
    u8 unk_7;  // 2 loads, 1 stores
    u8 unk_8;  // 2 loads, 1 stores
    u8 unk_9;  // 1 loads, 0 stores
    u8 unk_A;  // 1 loads, 0 stores
    u8 unk_B;  // 1 loads, 0 stores
    u32 unk_C;  // 1 loads, 0 stores
    u8 pad_10[0x4];
    u32 unk_14;  // 2 loads, 0 stores
    u8 pad_18[0xBEC];
} Obj_3_bss_A17D4;
extern Obj_3_bss_A17D4 lbl_3_bss_A17D4;

// lbl_3_bss_A1768: .bss size 0x4, 3 refs from emblem.c
extern u32 lbl_3_bss_A1768;

// lbl_3_bss_A17CC: .bss size 0x2, 2 refs from emblem.c
extern s16 lbl_3_bss_A17CC;

// lbl_3_bss_A176C: .bss size 0x4, 2 refs from emblem.c
extern u32 lbl_3_bss_A176C;

#endif  // REL_CUSTOMIZE_EMBLEM_H
