#ifndef REL_CUSTOMIZE_GLOBALS_H
#define REL_CUSTOMIZE_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module customize`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_3_bss_F0: .bss size 0x30, referenced by 40 functions, shape {'object': 206}
typedef struct {
    u8 unk_0;  // 12 loads, 2 stores
    u8 unk_1;  // 1 loads, 0 stores
    u8 pad_2[0x2];
    s16 unk_4;  // 3 loads, 1 stores
    s16 unk_6;  // 6 loads, 0 stores
    s16 unk_8;  // 19 loads, 0 stores
    s16 unk_A;  // 41 loads, 0 stores
    s16 unk_C;  // 9 loads, 0 stores
    s16 unk_E;  // 1 loads, 0 stores
    u8 pad_10[0x14];
    u32 unk_24;  // 39 loads, 4 stores
    s16 unk_28;  // 3 loads, 1 stores
    s16 unk_2A;  // 30 loads, 2 stores
    s16 unk_2C;  // 31 loads, 1 stores
    u8 pad_2E[0x2];
} Obj_3_bss_F0;
extern Obj_3_bss_F0 lbl_3_bss_F0;

// lbl_3_bss_140: .bss size 0x20704, referenced by 30 functions, shape {'object': 20}
typedef struct {
    u32 unk_0;  // 5 loads, 0 stores
    u8 pad_4[0x1];
    u8 unk_5;  // 2 loads, 3 stores
    u8 pad_6[0x1];
    u8 unk_7;  // 5 loads, 0 stores
    u8 unk_8;  // 0 loads, 5 stores
    u8 pad_9[0x206FB];
} Obj_3_bss_140;
extern Obj_3_bss_140 lbl_3_bss_140;

// lbl_3_bss_0: .bss size 0x8, referenced by 26 functions, shape {'object': 365}
typedef struct {
    u32 unk_0;  // 1 loads, 12 stores
    u32 unk_4;  // 1 loads, 1 stores
} Obj_3_bss_0;
extern Obj_3_bss_0 lbl_3_bss_0;

// lbl_3_data_0: .data size 0xA8, referenced by 22 functions, shape {'object': 109}
typedef struct {
    u16 unk_0;  // 4 loads, 0 stores
    u8 pad_2[0x6];
    u16 unk_8;  // 4 loads, 0 stores
    u8 pad_A[0x6];
    u16 unk_10;  // 4 loads, 0 stores
    u16 unk_12;  // 8 loads, 0 stores
    u8 pad_14[0x94];
} Obj_3_data_0;
extern Obj_3_data_0 lbl_3_data_0;

// lbl_3_bss_20850: .bss size 0x4, referenced by 22 functions, shape {'object': 29}
extern u32 lbl_3_bss_20850;

#endif  // REL_CUSTOMIZE_GLOBALS_H
