#ifndef REL_CUSTOMIZE_TOOLKIT_H
#define REL_CUSTOMIZE_TOOLKIT_H

#include "types.h"
#include "rel/customize/globals.h"

// Generated by `fzgx headers --module customize --tu toolkit.c`: globals of toolkit.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_3_bss_A2438: .bss size 0x1C, 17 refs from toolkit.c
typedef struct {
    u8 unk_0;  // 23 loads, 1 stores
    u8 pad_1[0x3];
    u32 unk_4;  // 3 loads, 14 stores
    u32 unk_8;  // 10 loads, 6 stores
    u8 unk_C;  // 13 loads, 2 stores
    u8 unk_D;  // 0 loads, 1 stores
    u8 unk_E;  // 1 loads, 13 stores
    u8 unk_F;  // 13 loads, 5 stores
    u8 unk_10;  // 14 loads, 14 stores
    u8 pad_11[0x1];
    s16 unk_12;  // 12 loads, 3 stores
    u8 unk_14;  // 9 loads, 3 stores
    u8 unk_15;  // 11 loads, 5 stores
    s16 unk_16;  // 3 loads, 2 stores
    s16 unk_18;  // 2 loads, 4 stores
    s16 unk_1A;  // 2 loads, 4 stores
} Obj_3_bss_A2438;
extern Obj_3_bss_A2438 lbl_3_bss_A2438;

// lbl_3_bss_20: .bss size 0xD0, 12 refs from toolkit.c
typedef struct {
    u8 unk_0;  // 12 loads, 6 stores
    u8 pad_1[0x3];
    u32 unk_4;  // 1 loads, 3 stores
    u8 unk_8;  // 3 loads, 0 stores
    u8 pad_9[0x7];
    u8 unk_10;  // 3 loads, 0 stores
    u8 pad_11[0x7];
    s16 unk_18;  // 15 loads, 0 stores
    s16 unk_1A;  // 12 loads, 7 stores
    s16 unk_1C;  // 1 loads, 0 stores
    s16 unk_1E;  // 1 loads, 0 stores
    s16 unk_20;  // 11 loads, 2 stores
    s16 unk_22;  // 10 loads, 4 stores
    s16 unk_24;  // 1 loads, 0 stores
    u8 pad_26[0x4];
    s16 unk_2A;  // 2 loads, 0 stores
    s16 unk_2C;  // 7 loads, 6 stores
    u8 pad_2E[0xA2];
} Obj_3_bss_20;
extern Obj_3_bss_20 lbl_3_bss_20;

// lbl_3_bss_A2460: .bss size 0x8, 11 refs from toolkit.c
typedef struct {
    s16 unk_0;  // 2 loads, 7 stores
    s16 unk_2;  // 2 loads, 7 stores
    s16 unk_4;  // 3 loads, 10 stores
    s16 unk_6;  // 2 loads, 7 stores
} Obj_3_bss_A2460;
extern Obj_3_bss_A2460 lbl_3_bss_A2460;

// lbl_3_bss_241E0: .bss size 0x190, 8 refs from toolkit.c
typedef struct {
    f32 unk_0;  // 0 loads, 8 stores
    f32 unk_4;  // 0 loads, 8 stores
    f32 unk_8;  // 0 loads, 7 stores
    f32 unk_C;  // 0 loads, 7 stores
    u8 pad_10[0x10];
    f32 unk_20;  // 7 loads, 0 stores
    f32 unk_24;  // 7 loads, 0 stores
    u8 pad_28[0x10];
    u8 unk_38;  // 0 loads, 8 stores
    u8 pad_39[0xF];
    f32 unk_48;  // 0 loads, 5 stores
    u8 pad_4C[0xC];
    u32 unk_58;  // 0 loads, 8 stores
    u8 pad_5C[0x134];
} Obj_3_bss_241E0;
extern Obj_3_bss_241E0 lbl_3_bss_241E0;

// lbl_3_bss_A2468: .bss size 0x24, 7 refs from toolkit.c
typedef struct {
    u8 pad_0[0x14];
    f32 unk_14;  // 0 loads, 2 stores
    u8 pad_18[0xC];
} Obj_3_bss_A2468;
extern Obj_3_bss_A2468 lbl_3_bss_A2468;

// lbl_3_data_4B70: .data size 0x4, 4 refs from toolkit.c (own data block)
extern u32 lbl_3_data_4B70;

// lbl_3_bss_6D8C0: .bss size 0x4B0, 4 refs from toolkit.c
typedef struct {
    u8 pad_0[0x2];
    s16 unk_2;  // 2 loads, 0 stores
    f32 unk_4;  // 2 loads, 0 stores
    s16 unk_8;  // 2 loads, 0 stores
    u8 pad_A[0x4A6];
} Obj_3_bss_6D8C0;
extern Obj_3_bss_6D8C0 lbl_3_bss_6D8C0;

// lbl_3_bss_2C584: .bss size 0x188, 4 refs from toolkit.c
typedef struct {
    s16 unk_0;  // 4 loads, 0 stores
    u8 pad_2[0x2];
    u32 unk_4;  // 6 loads, 1 stores
    u8 pad_8[0x180];
} Obj_3_bss_2C584;
extern Obj_3_bss_2C584 lbl_3_bss_2C584;

// lbl_3_data_C4: .data size 0x2, 4 refs from toolkit.c
extern s16 lbl_3_data_C4;

// lbl_3_bss_20848: .bss size 0x4, 4 refs from toolkit.c
extern u32 lbl_3_bss_20848;

// lbl_3_bss_7E23C: .bss size 0x2, 3 refs from toolkit.c
extern s16 lbl_3_bss_7E23C;

// lbl_3_bss_20854: .bss size 0xC, 3 refs from toolkit.c
typedef struct {
    u32 unk_0;  // 15 loads, 0 stores
    u8 pad_4[0x8];
} Obj_3_bss_20854;
extern Obj_3_bss_20854 lbl_3_bss_20854;

// lbl_3_bss_18: .bss size 0x8, 3 refs from toolkit.c
extern s16 lbl_3_bss_18;

// lbl_3_data_4648: .data size 0x528, 3 refs from toolkit.c (own data block)
typedef struct {
    u32 unk_0;  // 5 loads, 0 stores
    u8 pad_4[0x524];
} Obj_3_data_4648;
extern Obj_3_data_4648 lbl_3_data_4648;

// lbl_3_data_4B84: .data size 0x14, 3 refs from toolkit.c (own data block)
extern u8 lbl_3_data_4B84[0x14];

// lbl_3_bss_A2454: .bss size 0x4, 3 refs from toolkit.c
extern u32 lbl_3_bss_A2454;

// lbl_3_bss_2C7C0: .bss size 0x41100, 3 refs from toolkit.c
typedef struct {
    u8 pad_0[0x390];
    u32 unk_390;  // 2 loads, 2 stores
    u8 pad_394[0xC];
    u32 unk_3A0;  // 0 loads, 2 stores
    u32 unk_3A4;  // 2 loads, 0 stores
} Obj_3_bss_2C7C0_At0;
typedef struct {
    Obj_3_bss_2C7C0_At0 *unk_0;  // 2 loads, 1 stores
    u8 unk_4;  // 0 loads, 1 stores
    u8 pad_5[0x7];
    u32 unk_C;  // 0 loads, 2 stores
    u8 pad_10[0x410F0];
} Obj_3_bss_2C7C0;
extern Obj_3_bss_2C7C0 lbl_3_bss_2C7C0;

// lbl_3_bss_7E084: .bss size 0x1B8, 2 refs from toolkit.c
typedef struct {
    s16 unk_0;  // 1 loads, 0 stores
    s16 unk_2;  // 3 loads, 0 stores
    s16 unk_4;  // 1 loads, 0 stores
    u8 pad_6[0x1B2];
} Obj_3_bss_7E084;
extern Obj_3_bss_7E084 lbl_3_bss_7E084;

// lbl_3_data_4B74: .data size 0xE, 2 refs from toolkit.c (own data block)
extern u8 lbl_3_data_4B74[0xE];

// lbl_3_bss_7EBA0: .bss size 0x2, 2 refs from toolkit.c
extern s16 lbl_3_bss_7EBA0;

// lbl_3_bss_A248C: .bss size 0x2A, 2 refs from toolkit.c
typedef struct {
    s16 unk_0;  // 1 loads, 1 stores
    s16 unk_2;  // 1 loads, 1 stores
    s16 unk_4;  // 1 loads, 1 stores
    s16 unk_6;  // 1 loads, 1 stores
    u8 pad_8[0x22];
} Obj_3_bss_A248C;
extern Obj_3_bss_A248C lbl_3_bss_A248C;

// lbl_3_bss_7E6F0: .bss size 0x4B0, 2 refs from toolkit.c
typedef struct {
    s16 unk_0;  // 4 loads, 0 stores
    s16 unk_2;  // 3 loads, 0 stores
    f32 unk_4;  // 1 loads, 0 stores
    s16 unk_8;  // 1 loads, 0 stores
    s16 unk_A;  // 1 loads, 0 stores
    u8 pad_C[0x4A4];
} Obj_3_bss_7E6F0;
extern Obj_3_bss_7E6F0 lbl_3_bss_7E6F0;

// lbl_3_bss_6DE20: .bss size 0xFD40, 2 refs from toolkit.c
extern u8 lbl_3_bss_6DE20[0xFD40];

// lbl_3_data_3D50: .data size 0x9, 2 refs from toolkit.c (own data block)
extern u8 lbl_3_data_3D50[0x9];

// lbl_3_data_4B98: .data size 0x7, 2 refs from toolkit.c (own data block)
extern u32 lbl_3_data_4B98;

// lbl_3_bss_A179C: .bss size 0x4, 2 refs from toolkit.c
extern u32 lbl_3_bss_A179C;

// lbl_3_data_3D14: .data size 0x3C, 2 refs from toolkit.c (own data block)
extern u8 lbl_3_data_3D14[0x3C];

// lbl_3_bss_21960: .bss size 0x2880, 2 refs from toolkit.c
extern u8 lbl_3_bss_21960[0x2880];

// lbl_3_data_4BA0: .data size 0x14, 1 refs from toolkit.c (own data block)
extern u8 lbl_3_data_4BA0[0x14];

#endif  // REL_CUSTOMIZE_TOOLKIT_H
