#ifndef REL_TITLE_GLOBALS_H
#define REL_TITLE_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module title`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_8_bss_2A8: .bss size 0x2, referenced by 21 functions, shape {'object': 269}
extern u32 lbl_8_bss_2A8;

#endif  // REL_TITLE_GLOBALS_H
