#ifndef REL_TITLE_NAME_ENTRY_H
#define REL_TITLE_NAME_ENTRY_H

#include "types.h"
#include "rel/title/globals.h"

// Generated by `fzgx headers --module title --tu name_entry.c`: globals of name_entry.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_8_bss_550: .bss size 0x4, 3 refs from name_entry.c
typedef struct {
    u32 unk_0;  // 11 loads, 6 stores
    u32 unk_4;  // 1 loads, 1 stores
    u32 unk_8;  // 4 loads, 1 stores
    u8 unk_C;  // 8 loads, 1 stores
    u8 unk_D;  // 5 loads, 4 stores
    u8 unk_E;  // 10 loads, 3 stores
    u8 unk_F;  // 3 loads, 12 stores
    u8 unk_10;  // 1 loads, 0 stores
    u8 unk_11;  // 2 loads, 1 stores
    u16 unk_12;  // 3 loads, 3 stores
    u8 unk_14;  // 2 loads, 2 stores
    u8 unk_15;  // 2 loads, 2 stores
    u8 unk_16;  // 2 loads, 2 stores
    u8 unk_17;  // 2 loads, 2 stores
    u32 unk_18;  // 1 loads, 1 stores
    u32 unk_1C;  // 1 loads, 1 stores
    u32 unk_20;  // 3 loads, 2 stores
    u8 pad_24[0x4];
    u8 unk_28;  // 1 loads, 0 stores
    u8 pad_29[0xD];
    u8 unk_36;  // 2 loads, 1 stores
    u8 unk_37;  // 0 loads, 1 stores
    u8 pad_38[0x2];
    u8 unk_3A;  // 2 loads, 2 stores
    u8 unk_3B;  // 5 loads, 2 stores
    u32 unk_3C;  // 4 loads, 2 stores
} Obj_8_bss_550_Target;
extern Obj_8_bss_550_Target *lbl_8_bss_550;

// lbl_8_data_A288: .data size 0x40, 1 refs from name_entry.c (own data block)
extern u8 lbl_8_data_A288[0x40];

// lbl_8_data_A2C8: .data size 0x18, 1 refs from name_entry.c (own data block)
extern u8 lbl_8_data_A2C8[0x18];

// lbl_8_data_A2E0: .data size 0x70, 1 refs from name_entry.c (own data block)
extern u8 lbl_8_data_A2E0[0x70];

#endif  // REL_TITLE_NAME_ENTRY_H
