#ifndef REL_TITLE_OPERATION_H
#define REL_TITLE_OPERATION_H

#include "types.h"
#include "rel/title/globals.h"

// Generated by `fzgx headers --module title --tu operation.c`: globals of operation.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_8_data_7E50: .data size 0x4, 13 refs from operation.c
extern u32 lbl_8_data_7E50;

// lbl_8_bss_3CC: .bss size 0x4, 8 refs from operation.c
extern u32 lbl_8_bss_3CC;

// lbl_8_bss_3D0: .bss size 0x170, 8 refs from operation.c
typedef struct {
    u32 unk_0;  // 25 loads, 0 stores
    u8 pad_4[0x16C];
} Obj_8_bss_3D0;
extern Obj_8_bss_3D0 lbl_8_bss_3D0;

// lbl_8_data_A1E8: .data size 0xA0, 5 refs from operation.c (own data block)
extern u8 lbl_8_data_A1E8[0xA0];

// lbl_8_bss_550: .bss size 0x4, 5 refs from operation.c
typedef struct {
    u32 unk_0;  // 11 loads, 6 stores
    u32 unk_4;  // 1 loads, 1 stores
    u32 unk_8;  // 4 loads, 1 stores
    u8 unk_C;  // 8 loads, 1 stores
    u8 unk_D;  // 5 loads, 4 stores
    u8 unk_E;  // 10 loads, 3 stores
    u8 unk_F;  // 3 loads, 12 stores
    u8 unk_10;  // 1 loads, 0 stores
    u8 unk_11;  // 2 loads, 1 stores
    u16 unk_12;  // 3 loads, 3 stores
    u8 unk_14;  // 2 loads, 2 stores
    u8 unk_15;  // 2 loads, 2 stores
    u8 unk_16;  // 2 loads, 2 stores
    u8 unk_17;  // 2 loads, 2 stores
    u32 unk_18;  // 1 loads, 1 stores
    u32 unk_1C;  // 1 loads, 1 stores
    u32 unk_20;  // 3 loads, 2 stores
    u8 pad_24[0x4];
    u8 unk_28;  // 1 loads, 0 stores
    u8 pad_29[0xD];
    u8 unk_36;  // 2 loads, 1 stores
    u8 unk_37;  // 0 loads, 1 stores
    u8 pad_38[0x2];
    u8 unk_3A;  // 2 loads, 2 stores
    u8 unk_3B;  // 5 loads, 2 stores
    u32 unk_3C;  // 4 loads, 2 stores
} Obj_8_bss_550_Target;
extern Obj_8_bss_550_Target *lbl_8_bss_550;

// lbl_8_data_8AD4: .data size 0x124, 4 refs from operation.c (own data block)
extern u8 lbl_8_data_8AD4[0x124];

// lbl_8_bss_2C0: .bss size 0x10C, 2 refs from operation.c
typedef struct {
    u32 unk_0;  // 2 loads, 3 stores
    u8 pad_4[0x108];
} Obj_8_bss_2C0;
extern Obj_8_bss_2C0 lbl_8_bss_2C0;

// lbl_8_bss_554: .bss size 0x1, 2 refs from operation.c
extern u8 lbl_8_bss_554;

// lbl_8_bss_2B0: .bss size 0x4, 2 refs from operation.c
extern u32 lbl_8_bss_2B0;

// lbl_8_data_9B8C: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_9B8C[0x18];

// lbl_8_data_9AB8: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_9AB8[0x18];

// lbl_8_data_99BC: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_99BC[0x18];

// lbl_8_data_96AC: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_96AC[0x18];

// lbl_8_data_95B8: .data size 0xB0, 1 refs from operation.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u32 unk_4;  // 2 loads, 0 stores
    u32 unk_8;  // 2 loads, 0 stores
    u32 unk_C;  // 2 loads, 0 stores
    u32 unk_10;  // 2 loads, 0 stores
    u32 unk_14;  // 2 loads, 0 stores
    u32 unk_18;  // 1 loads, 0 stores
    u32 unk_1C;  // 1 loads, 0 stores
    u8 pad_20[0x90];
} Obj_8_data_95B8;
extern Obj_8_data_95B8 lbl_8_data_95B8;

// lbl_8_data_9E04: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_9E04[0x18];

// lbl_8_data_A01C: .data size 0xA4, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_A01C[0xA4];

// lbl_8_data_A0C0: .data size 0x1, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_A0C0;

// lbl_8_data_990C: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_990C[0x18];

// lbl_8_data_9778: .data size 0x18, 1 refs from operation.c (own data block)
extern u8 lbl_8_data_9778[0x18];

// lbl_8_data_9270: .data size 0x28, 1 refs from operation.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u32 unk_4;  // 2 loads, 0 stores
    u32 unk_8;  // 2 loads, 0 stores
    u32 unk_C;  // 2 loads, 0 stores
    u32 unk_10;  // 2 loads, 0 stores
    u32 unk_14;  // 2 loads, 0 stores
    u32 unk_18;  // 1 loads, 0 stores
    u32 unk_1C;  // 1 loads, 0 stores
    u8 pad_20[0x8];
} Obj_8_data_9270;
extern Obj_8_data_9270 lbl_8_data_9270;

#endif  // REL_TITLE_OPERATION_H
