#ifndef REL_TITLE_TITLE_H
#define REL_TITLE_TITLE_H

#include "types.h"
#include "rel/title/globals.h"

// Generated by `fzgx headers --module title --tu title.c`: globals of title.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_8_bss_0: .bss size 0x1, 16 refs from title.c
extern u8 lbl_8_bss_0;

// lbl_8_data_0: .data size 0x4, 5 refs from title.c
extern u32 lbl_8_data_0;

// lbl_8_bss_3D0: .bss size 0x170, 5 refs from title.c
typedef struct {
    u32 unk_0;  // 25 loads, 0 stores
    u8 pad_4[0x16C];
} Obj_8_bss_3D0;
extern Obj_8_bss_3D0 lbl_8_bss_3D0;

// lbl_8_bss_3CC: .bss size 0x4, 5 refs from title.c
extern u32 lbl_8_bss_3CC;

// lbl_8_data_434: .data size 0x44, 4 refs from title.c (own data block)
extern u8 lbl_8_data_434[0x44];

// lbl_8_bss_238: .bss size 0x5, 3 refs from title.c
extern u32 lbl_8_bss_238;

// lbl_8_bss_242: .bss size 0x66, 2 refs from title.c
typedef struct {
    u8 unk_0;  // 0 loads, 2 stores
    u8 pad_1[0x65];
} Obj_8_bss_242;
extern Obj_8_bss_242 lbl_8_bss_242;

// lbl_8_bss_234: .bss size 0x4, 2 refs from title.c
extern u32 lbl_8_bss_234;

// lbl_8_bss_2: .bss size 0x1, 2 refs from title.c
extern u8 lbl_8_bss_2;

// lbl_8_bss_2B0: .bss size 0x4, 2 refs from title.c
extern u32 lbl_8_bss_2B0;

// lbl_8_bss_2AC: .bss size 0x4, 2 refs from title.c
extern u32 lbl_8_bss_2AC;

// lbl_8_bss_23D: .bss size 0x1, 2 refs from title.c
extern u8 lbl_8_bss_23D;

// lbl_8_data_62D0: .data size 0xA98, 2 refs from title.c (own data block)
typedef struct {
    u32 unk_0;  // 8 loads, 0 stores
    u8 pad_4[0xA94];
} Obj_8_data_62D0;
extern Obj_8_data_62D0 lbl_8_data_62D0;

// lbl_8_data_7C14: .data size 0x20, 2 refs from title.c (own data block)
extern u8 lbl_8_data_7C14[0x20];

// lbl_8_data_7E50: .data size 0x4, 1 refs from title.c (own data block)
extern u32 lbl_8_data_7E50;

// lbl_8_data_81BC: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_81BC[0x18];

// lbl_8_data_81F0: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_81F0[0x18];

// jumptable_8_data_494: .data size 0x3C, 1 refs from title.c (own data block)
extern u8 jumptable_8_data_494[0x3C];

// lbl_8_data_478: .data size 0x1B, 1 refs from title.c (own data block)
extern u8 lbl_8_data_478[0x1B];

// lbl_8_data_8224: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_8224[0x18];

// lbl_8_data_8258: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_8258[0x18];

// lbl_8_data_84EC: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_84EC[0x18];

// lbl_8_data_8554: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_8554[0x18];

// lbl_8_data_7CDC: .data size 0x174, 1 refs from title.c (own data block)
extern u8 lbl_8_data_7CDC[0x174];

// jumptable_8_data_7C34: .data size 0xA8, 1 refs from title.c (own data block)
extern u8 jumptable_8_data_7C34[0xA8];

// lbl_8_data_8458: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_8458[0x18];

// lbl_8_data_84B8: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_84B8[0x18];

// lbl_8_data_87DC: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_87DC[0x18];

// lbl_8_data_8840: .data size 0x18, 1 refs from title.c (own data block)
extern u8 lbl_8_data_8840[0x18];

#endif  // REL_TITLE_TITLE_H
