/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "dolphin/dvd/SharedState.h"

extern DVDLowBuffer __DVDLowPrev;
extern DVDLowBuffer __DVDLowCurr;



__declspec(section ".data") DVDLowBuffer __DVDLowCurr __attribute__((aligned(4)));



__declspec(section ".data") DVDLowBuffer __DVDLowPrev __attribute__((aligned(8)));
