/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "dolphin/dvd/SharedState.h"

extern OSAlarm __DVDLowAlarmForWA;



__declspec(section ".data") OSAlarm __DVDLowAlarmForWA __attribute__((aligned(8)));
