/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "dol/data/__files.h"

#include "dol/data/__files.h"



extern u8 lbl_801A33B8[];
extern u8 lbl_801A34B8[];
extern u8 lbl_801A35B8[];
extern void fn_8008580C(void);
extern void fn_80085814(void);
extern void fn_8008DCCC(void);
#pragma explicit_zero_data on
__declspec(section ".data") Data___files __files __attribute__((aligned(8))) = {
    0x00000000U,
    0x0A800000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    (u8 *)&lbl_801A35B8,
    0x00000100U,
    (u8 *)&lbl_801A35B8,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_8008DCCC,
    fn_80085814,
    fn_8008580C,
    0x00000000U,
    (u8 *)&__files + 80,
    0x00000001U,
    0x12800000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    (u8 *)&lbl_801A34B8,
    0x00000100U,
    (u8 *)&lbl_801A34B8,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_8008DCCC,
    fn_80085814,
    fn_8008580C,
    0x00000000U,
    (u8 *)&__files + 160,
    0x00000002U,
    0x10800000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    (u8 *)&lbl_801A33B8,
    0x00000100U,
    (u8 *)&lbl_801A33B8,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_8008DCCC,
    fn_80085814,
    fn_8008580C,
    0x00000000U,
    (u8 *)&__files + 240,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U
};
#pragma explicit_zero_data reset
