/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "dolphin/dvd/SharedState.h"

extern DVDCommandBlock __OSDriveBlock;



__declspec(section ".data") DVDCommandBlock __OSDriveBlock __attribute__((aligned(8)));
