/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern u32 lbl_3_bss_2C7C0[66624];



__declspec(section ".data") u32 lbl_3_bss_2C7C0[66624] __attribute__((aligned(32)));
