#ifndef REL_WINNING_GLOBALS_H
#define REL_WINNING_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module winning`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_15_bss_0: .bss size 0x2, referenced by 27 functions, shape {'object': 489}
extern u16 lbl_15_bss_0;

#endif  // REL_WINNING_GLOBALS_H
