#ifndef REL_WINNING_WINNING_H
#define REL_WINNING_WINNING_H

#include "types.h"
#include "rel/winning/globals.h"

// Generated by `fzgx headers --module winning --tu winning.c`: globals of winning.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_15_data_0: .data size 0x8, 10 refs from winning.c
extern u32 lbl_15_data_0;

// lbl_15_data_A4: .data size 0xB0, 6 refs from winning.c (own data block)
extern u8 lbl_15_data_A4[0xB0];

// lbl_15_bss_14: .bss size 0x8, 4 refs from winning.c
extern u32 lbl_15_bss_14;

// lbl_15_data_90: .data size 0x14, 2 refs from winning.c
typedef struct {
    u8 pad_0[0x4];
    u32 unk_4;  // 8 loads, 0 stores
    u32 unk_8;  // 4 loads, 0 stores
    u32 unk_C;  // 2 loads, 0 stores
    u32 unk_10;  // 1 loads, 0 stores
} Obj_15_data_90;
extern Obj_15_data_90 lbl_15_data_90;

// jumptable_15_data_1DC: .data size 0x64, 1 refs from winning.c (own data block)
extern u8 jumptable_15_data_1DC[0x64];

// jumptable_15_data_1F20: .data size 0x50, 1 refs from winning.c (own data block)
extern u8 jumptable_15_data_1F20[0x50];

// lbl_15_data_154: .data size 0xE, 1 refs from winning.c (own data block)
extern u8 lbl_15_data_154[0xE];

// lbl_15_data_164: .data size 0x78, 1 refs from winning.c (own data block)
extern u8 lbl_15_data_164[0x78];

#endif  // REL_WINNING_WINNING_H
