#ifndef REL_MOVIE_MOVIE_H
#define REL_MOVIE_MOVIE_H

#include "types.h"
#include "rel/movie/globals.h"

// Generated by `fzgx headers --module movie --tu movie.c`: globals of movie.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_5_bss_0: .bss size 0x20, 3 refs from movie.c
typedef struct {
    u32 unk_0;  // 14 loads, 0 stores
} Obj_5_bss_0_At0;
typedef struct {
    Obj_5_bss_0_At0 *unk_0;  // 19 loads, 3 stores
    u32 unk_4;  // 2 loads, 3 stores
    u32 unk_8;  // 2 loads, 5 stores
    u32 unk_C;  // 3 loads, 3 stores
    u8 unk_10;  // 2 loads, 6 stores
    u8 unk_11;  // 1 loads, 4 stores
    u8 unk_12;  // 6 loads, 2 stores
    u8 unk_13;  // 30 loads, 3 stores
    u8 unk_14;  // 5 loads, 3 stores
    u8 pad_15[0x3];
    u32 unk_18;  // 5 loads, 6 stores
    u8 unk_1C;  // 1 loads, 11 stores
    u8 pad_1D[0x3];
} Obj_5_bss_0;
extern Obj_5_bss_0 lbl_5_bss_0;

// lbl_5_bss_B90: .bss size 0x28, 2 refs from movie.c
typedef struct {
    u32 unk_0;  // 2 loads, 3 stores
    u8 pad_4[0x24];
} Obj_5_bss_B90;
extern Obj_5_bss_B90 lbl_5_bss_B90;

// lbl_5_data_1784: .data size 0x12, 1 refs from movie.c (own data block)
extern u8 lbl_5_data_1784[0x12];

// lbl_5_data_14: .data size 0x2C, 1 refs from movie.c (own data block)
extern u8 lbl_5_data_14[0x2C];

#endif  // REL_MOVIE_MOVIE_H
