#ifndef REL_STORY_GLOBALS_H
#define REL_STORY_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module story`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

#endif  // REL_STORY_GLOBALS_H
