#ifndef REL_STORY_STORY_MODE_H
#define REL_STORY_STORY_MODE_H

#include "types.h"
#include "rel/story/globals.h"

// Generated by `fzgx headers --module story --tu story_mode.c`: globals of story_mode.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_7_bss_0: .bss size 0x4, 16 refs from story_mode.c
extern u32 lbl_7_bss_0;

// lbl_7_bss_10: .bss size 0x4, 8 refs from story_mode.c
typedef struct {
    u8 unk_0;  // 11 loads, 4 stores
    u8 unk_1;  // 9 loads, 1 stores
    u8 pad_2[0x2];
    u16 unk_4;  // 0 loads, 1 stores
    u8 unk_6;  // 0 loads, 1 stores
    u8 unk_7;  // 0 loads, 1 stores
    u32 unk_8;  // 0 loads, 5 stores
} Obj_7_bss_10_Target;
extern Obj_7_bss_10_Target *lbl_7_bss_10;

// lbl_7_data_0: .data size 0x2A0, 5 refs from story_mode.c
extern u8 lbl_7_data_0[0x2A0];

// lbl_7_bss_1960: .bss size 0x111, 5 refs from story_mode.c
typedef struct {
    u32 unk_0;  // 4 loads, 5 stores
    u8 pad_4[0x8];
    u8 unk_C;  // 1 loads, 0 stores
    u8 unk_D;  // 1 loads, 0 stores
} Obj_7_bss_1960_At4;
typedef struct {
    u8 unk_0;  // 6 loads, 3 stores
    u8 pad_1[0x3];
    Obj_7_bss_1960_At4 *unk_4;  // 5 loads, 1 stores
    u8 unk_8;  // 1 loads, 2 stores
    u8 pad_9[0x3];
    u32 unk_C;  // 8 loads, 19 stores
    u32 unk_10;  // 0 loads, 1 stores
    u32 unk_14;  // 0 loads, 1 stores
    u8 unk_18;  // 0 loads, 1 stores
    u8 unk_19;  // 0 loads, 1 stores
    u8 pad_1A[0x2];
    f32 unk_1C;  // 0 loads, 1 stores
    f32 unk_20;  // 0 loads, 1 stores
    f32 unk_24;  // 0 loads, 1 stores
    f32 unk_28;  // 0 loads, 1 stores
    u8 unk_2C;  // 3 loads, 2 stores
    u8 pad_2D[0x3];
    u32 unk_30;  // 1 loads, 1 stores
    u8 unk_34;  // 3 loads, 2 stores
    u8 unk_35;  // 2 loads, 1 stores
    u8 unk_36;  // 1 loads, 1 stores
    u8 unk_37;  // 1 loads, 1 stores
    u8 unk_38;  // 12 loads, 1 stores
    u8 unk_39;  // 1 loads, 1 stores
    u8 unk_3A;  // 1 loads, 1 stores
    u8 pad_3B[0x1];
    u32 unk_3C;  // 1 loads, 1 stores
    u8 unk_40;  // 0 loads, 1 stores
    u8 unk_41;  // 0 loads, 1 stores
    u8 unk_42;  // 0 loads, 1 stores
    u8 unk_43;  // 0 loads, 1 stores
    u8 unk_44;  // 0 loads, 1 stores
    u8 unk_45;  // 0 loads, 1 stores
    u8 unk_46;  // 0 loads, 1 stores
    u8 unk_47;  // 0 loads, 1 stores
    u32 unk_48;  // 0 loads, 1 stores
    u32 unk_4C;  // 0 loads, 1 stores
    u32 unk_50;  // 0 loads, 1 stores
    u32 unk_54;  // 0 loads, 1 stores
    u8 unk_58;  // 0 loads, 1 stores
    u8 unk_59;  // 2 loads, 1 stores
    u8 unk_5A;  // 0 loads, 1 stores
    u8 unk_5B;  // 0 loads, 1 stores
    u8 unk_5C;  // 0 loads, 1 stores
    u8 unk_5D;  // 0 loads, 1 stores
    u8 pad_5E[0x1A];
    u8 unk_78;  // 0 loads, 1 stores
    u8 unk_79;  // 0 loads, 1 stores
    u8 unk_7A;  // 0 loads, 1 stores
    u8 unk_7B;  // 0 loads, 1 stores
    u8 unk_7C;  // 0 loads, 1 stores
    u8 unk_7D;  // 0 loads, 1 stores
    u8 pad_7E[0x1A];
    u32 unk_98;  // 0 loads, 1 stores
    u32 unk_9C;  // 0 loads, 1 stores
    u32 unk_A0;  // 0 loads, 1 stores
    u32 unk_A4;  // 0 loads, 1 stores
    u32 unk_A8;  // 0 loads, 1 stores
    u32 unk_AC;  // 0 loads, 1 stores
    u8 pad_B0[0x61];
} Obj_7_bss_1960;
extern Obj_7_bss_1960 lbl_7_bss_1960;

// lbl_7_bss_14: .bss size 0x4, 4 refs from story_mode.c
typedef struct {
    u8 pad_0[0x1];
    u8 unk_1;  // 3 loads, 0 stores
    u8 pad_2[0x16];
    u32 unk_18;  // 1 loads, 0 stores
    u32 unk_1C;  // 1 loads, 0 stores
    u8 pad_20[0x4];
    u32 unk_24;  // 1 loads, 0 stores
} Obj_7_bss_14_Target;
extern Obj_7_bss_14_Target *lbl_7_bss_14;

// lbl_7_data_13FFC: .data size 0xF, 3 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13FFC[0xF];

// lbl_7_data_13F20: .data size 0xC, 3 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13F20[0xC];

// lbl_7_data_13A3C: .data size 0xD, 3 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13A3C[0xD];

// lbl_7_data_13A14: .data size 0x28, 2 refs from story_mode.c
extern u8 lbl_7_data_13A14[0x28];

// lbl_7_bss_1C: .bss size 0x2C, 2 refs from story_mode.c
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x28];
} Obj_7_bss_1C;
extern Obj_7_bss_1C lbl_7_bss_1C;

// lbl_7_bss_29C: .bss size 0x16C4, 2 refs from story_mode.c
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u8 pad_4[0x16C0];
} Obj_7_bss_29C;
extern Obj_7_bss_29C lbl_7_bss_29C;

// lbl_7_bss_48: .bss size 0x254, 2 refs from story_mode.c
typedef struct {
    u8 pad_0[0x244];
    u32 unk_244;  // 1 loads, 0 stores
    u8 pad_248[0xC];
} Obj_7_bss_48;
extern Obj_7_bss_48 lbl_7_bss_48;

// lbl_7_data_13E10: .data size 0xDC, 2 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13E10[0xDC];

// lbl_7_data_13DE0: .data size 0x17, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13DE0[0x17];

// lbl_7_data_13DF8: .data size 0x17, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13DF8[0x17];

// jumptable_7_data_1400C: .data size 0x48, 1 refs from story_mode.c (own data block)
extern u8 jumptable_7_data_1400C[0x48];

// lbl_7_data_13EEC: .data size 0x34, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13EEC[0x34];

// lbl_7_data_13F70: .data size 0x70, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13F70[0x70];

// lbl_7_data_13A4C: .data size 0xA, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13A4C[0xA];

// lbl_7_data_13A58: .data size 0x388, 1 refs from story_mode.c (own data block)
typedef struct {
    u8 pad_0[0x20];
    u32 unk_20;  // 1 loads, 0 stores
    u32 unk_24;  // 1 loads, 0 stores
    u32 unk_28;  // 1 loads, 0 stores
    u8 pad_2C[0x35C];
} Obj_7_data_13A58;
extern Obj_7_data_13A58 lbl_7_data_13A58;

// lbl_7_data_13FE0: .data size 0x1C, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_13FE0[0x1C];

// jumptable_7_data_140C0: .data size 0x64, 1 refs from story_mode.c (own data block)
extern u8 jumptable_7_data_140C0[0x64];

// lbl_7_data_14054: .data size 0xE, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_14054[0xE];

// jumptable_7_data_140A4: .data size 0x1C, 1 refs from story_mode.c (own data block)
extern u8 jumptable_7_data_140A4[0x1C];

// lbl_7_data_14064: .data size 0x15, 1 refs from story_mode.c (own data block)
extern u8 lbl_7_data_14064[0x15];

// jumptable_7_data_1407C: .data size 0x28, 1 refs from story_mode.c (own data block)
extern u8 jumptable_7_data_1407C[0x28];

#endif  // REL_STORY_STORY_MODE_H
