#ifndef REL_SEL_GLOBALS_H
#define REL_SEL_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module sel`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_10_bss_0: .bss size 0x14, referenced by 35 functions, shape {'object': 139}
typedef struct {
    u32 unk_0;  // 2 loads, 1 stores
    u32 unk_4;  // 2 loads, 1 stores
    s16 unk_8;  // 1 loads, 6 stores
    s16 unk_A;  // 2 loads, 8 stores
    u8 unk_C;  // 4 loads, 9 stores
    u8 pad_D[0x3];
    u32 unk_10;  // 1 loads, 1 stores
} Obj_10_bss_0;
extern Obj_10_bss_0 lbl_10_bss_0;

// lbl_10_bss_49388: .bss size 0x4, referenced by 28 functions, shape {'object': 39}
extern u32 lbl_10_bss_49388;

#endif  // REL_SEL_GLOBALS_H
