#ifndef REL_SEL_NAME_ENTRY_H
#define REL_SEL_NAME_ENTRY_H

#include "types.h"
#include "rel/sel/globals.h"

// Generated by `fzgx headers --module sel --tu name_entry.c`: globals of name_entry.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_10_bss_55CD8: .bss size 0x4, 3 refs from name_entry.c
typedef struct {
    u32 unk_0;  // 12 loads, 7 stores
    u32 unk_4;  // 1 loads, 1 stores
    u32 unk_8;  // 5 loads, 1 stores
    u8 unk_C;  // 8 loads, 1 stores
    u8 unk_D;  // 5 loads, 4 stores
    u8 unk_E;  // 10 loads, 4 stores
    u8 unk_F;  // 3 loads, 12 stores
    u8 unk_10;  // 1 loads, 0 stores
    u8 unk_11;  // 2 loads, 1 stores
    u16 unk_12;  // 3 loads, 3 stores
    u8 unk_14;  // 2 loads, 2 stores
    u8 unk_15;  // 2 loads, 2 stores
    u8 unk_16;  // 2 loads, 2 stores
    u8 unk_17;  // 2 loads, 2 stores
    u32 unk_18;  // 1 loads, 1 stores
    u32 unk_1C;  // 1 loads, 1 stores
    u32 unk_20;  // 3 loads, 2 stores
    u8 pad_24[0x4];
    u8 unk_28;  // 2 loads, 0 stores
    u8 pad_29[0xD];
    u8 unk_36;  // 2 loads, 1 stores
    u8 unk_37;  // 0 loads, 1 stores
    u8 pad_38[0x2];
    u8 unk_3A;  // 2 loads, 2 stores
    u8 unk_3B;  // 5 loads, 2 stores
    u32 unk_3C;  // 4 loads, 2 stores
} Obj_10_bss_55CD8_Target;
extern Obj_10_bss_55CD8_Target *lbl_10_bss_55CD8;

// lbl_10_bss_55CE1: .bss size 0x1, 3 refs from name_entry.c
extern u8 lbl_10_bss_55CE1;

// lbl_10_bss_55CE2: .bss size 0x1, 3 refs from name_entry.c
extern u8 lbl_10_bss_55CE2;

// lbl_10_bss_55CE0: .bss size 0x1, 2 refs from name_entry.c
extern u8 lbl_10_bss_55CE0;

// lbl_10_data_6980: .data size 0x40, 1 refs from name_entry.c (own data block)
extern u8 lbl_10_data_6980[0x40];

// lbl_10_data_6B2C: .data size 0x18, 1 refs from name_entry.c (own data block)
extern u8 lbl_10_data_6B2C[0x18];

// lbl_10_data_69C0: .data size 0x18, 1 refs from name_entry.c (own data block)
extern u8 lbl_10_data_69C0[0x18];

// lbl_10_data_69D8: .data size 0x70, 1 refs from name_entry.c (own data block)
extern u8 lbl_10_data_69D8[0x70];

// lbl_10_data_6A48: .data size 0x20, 1 refs from name_entry.c (own data block)
extern u8 lbl_10_data_6A48[0x20];

#endif  // REL_SEL_NAME_ENTRY_H
