#ifndef REL_SEL_RECORD_H
#define REL_SEL_RECORD_H

#include "types.h"
#include "rel/sel/globals.h"

// Generated by `fzgx headers --module sel --tu record.c`: globals of record.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_10_data_6BD0: .data size 0x9, 1 refs from record.c (own data block)
extern u8 lbl_10_data_6BD0[0x9];

// lbl_10_data_6BDC: .data size 0x13, 1 refs from record.c (own data block)
extern u8 lbl_10_data_6BDC[0x13];

#endif  // REL_SEL_RECORD_H
