#ifndef REL_SEL_SEL_H
#define REL_SEL_SEL_H

#include "types.h"
#include "rel/sel/globals.h"

// Generated by `fzgx headers --module sel --tu sel.c`: globals of sel.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_10_bss_51740: .bss size 0x4, 14 refs from sel.c
extern u32 lbl_10_bss_51740;

// lbl_10_bss_1C: .bss size 0x3A4, 13 refs from sel.c
typedef struct {
    s16 unk_0;  // 11 loads, 4 stores
    u8 pad_2[0x2];
    u32 unk_4;  // 19 loads, 0 stores
    u8 pad_8[0x39C];
} Obj_10_bss_1C;
extern Obj_10_bss_1C lbl_10_bss_1C;

// lbl_10_bss_14: .bss size 0x4, 12 refs from sel.c
extern u32 lbl_10_bss_14;

// lbl_10_bss_3C0: .bss size 0x48FC0, 11 refs from sel.c
typedef struct {
    u32 unk_0;  // 3 loads, 0 stores
    u8 pad_4[0x3];
    u8 unk_7;  // 1 loads, 0 stores
    u8 pad_8[0x48FB8];
} Obj_10_bss_3C0;
extern Obj_10_bss_3C0 lbl_10_bss_3C0;

// lbl_10_bss_4938C: .bss size 0x2, 11 refs from sel.c
extern s16 lbl_10_bss_4938C;

// lbl_10_bss_51744: .bss size 0x4, 11 refs from sel.c
extern u32 lbl_10_bss_51744;

// lbl_10_data_D00: .data size 0x4, 9 refs from sel.c (own data block)
extern u32 lbl_10_data_D00;

// lbl_10_bss_55690: .bss size 0x8, 6 refs from sel.c
typedef struct {
    f32 unk_0;  // 7 loads, 2 stores
    f32 unk_4;  // 7 loads, 2 stores
} Obj_10_bss_55690;
extern Obj_10_bss_55690 lbl_10_bss_55690;

// lbl_10_data_0: .data size 0x4, 6 refs from sel.c
extern u32 lbl_10_data_0;

// lbl_10_bss_55CE0: .bss size 0x1, 6 refs from sel.c
extern u8 lbl_10_bss_55CE0;

// lbl_10_bss_5560C: .bss size 0x50, 6 refs from sel.c
typedef struct {
    u8 pad_0[0x12];
    u8 unk_12;  // 5 loads, 0 stores
    u8 pad_13[0x3D];
} Obj_10_bss_5560C;
extern Obj_10_bss_5560C lbl_10_bss_5560C;

// lbl_10_bss_18: .bss size 0x2, 5 refs from sel.c
extern s16 lbl_10_bss_18;

// lbl_10_bss_1A: .bss size 0x2, 5 refs from sel.c
extern s16 lbl_10_bss_1A;

// lbl_10_bss_493A0: .bss size 0x5B20, 5 refs from sel.c
extern u8 lbl_10_bss_493A0[0x5B20];

// lbl_10_bss_55CD8: .bss size 0x4, 5 refs from sel.c
typedef struct {
    u32 unk_0;  // 12 loads, 7 stores
    u32 unk_4;  // 1 loads, 1 stores
    u32 unk_8;  // 5 loads, 1 stores
    u8 unk_C;  // 8 loads, 1 stores
    u8 unk_D;  // 5 loads, 4 stores
    u8 unk_E;  // 10 loads, 4 stores
    u8 unk_F;  // 3 loads, 12 stores
    u8 unk_10;  // 1 loads, 0 stores
    u8 unk_11;  // 2 loads, 1 stores
    u16 unk_12;  // 3 loads, 3 stores
    u8 unk_14;  // 2 loads, 2 stores
    u8 unk_15;  // 2 loads, 2 stores
    u8 unk_16;  // 2 loads, 2 stores
    u8 unk_17;  // 2 loads, 2 stores
    u32 unk_18;  // 1 loads, 1 stores
    u32 unk_1C;  // 1 loads, 1 stores
    u32 unk_20;  // 3 loads, 2 stores
    u8 pad_24[0x4];
    u8 unk_28;  // 2 loads, 0 stores
    u8 pad_29[0xD];
    u8 unk_36;  // 2 loads, 1 stores
    u8 unk_37;  // 0 loads, 1 stores
    u8 pad_38[0x2];
    u8 unk_3A;  // 2 loads, 2 stores
    u8 unk_3B;  // 5 loads, 2 stores
    u32 unk_3C;  // 4 loads, 2 stores
} Obj_10_bss_55CD8_Target;
extern Obj_10_bss_55CD8_Target *lbl_10_bss_55CD8;

// lbl_10_data_68E0: .data size 0xA0, 5 refs from sel.c (own data block)
extern u8 lbl_10_data_68E0[0xA0];

// lbl_10_bss_55680: .bss size 0x1, 5 refs from sel.c
extern u8 lbl_10_bss_55680;

// lbl_10_data_5C1C: .data size 0x1C8, 4 refs from sel.c (own data block)
typedef struct {
    u32 unk_0;  // 20 loads, 0 stores
    u8 pad_4[0x1C4];
} Obj_10_data_5C1C;
extern Obj_10_data_5C1C lbl_10_data_5C1C;

// lbl_10_bss_5568C: .bss size 0x1, 4 refs from sel.c
extern u8 lbl_10_bss_5568C;

// lbl_10_bss_5174E: .bss size 0x2, 4 refs from sel.c
extern u16 lbl_10_bss_5174E;

// lbl_10_bss_55698: .bss size 0x448, 4 refs from sel.c
typedef struct {
    f32 unk_0;  // 5 loads, 0 stores
    f32 unk_4;  // 5 loads, 0 stores
    u8 pad_8[0x440];
} Obj_10_bss_55698;
extern Obj_10_bss_55698 lbl_10_bss_55698;

// lbl_10_bss_49380: .bss size 0x4, 4 refs from sel.c
extern u32 lbl_10_bss_49380;

// lbl_10_bss_4938E: .bss size 0x1, 4 refs from sel.c
extern u8 lbl_10_bss_4938E;

// lbl_10_data_57C: .data size 0x20, 4 refs from sel.c (own data block)
extern u8 lbl_10_data_57C[0x20];

// lbl_10_bss_51B7C: .bss size 0x1380, 4 refs from sel.c
extern u8 lbl_10_bss_51B7C[0x1380];

// lbl_10_bss_52EFC: .bss size 0x2700, 4 refs from sel.c
extern u8 lbl_10_bss_52EFC[0x2700];

// lbl_10_bss_5197C: .bss size 0x200, 4 refs from sel.c
typedef struct {
    u8 pad_0[0x30];
    u16 unk_30;  // 2 loads, 0 stores
    u16 unk_32;  // 2 loads, 0 stores
    u32 unk_34;  // 2 loads, 0 stores
    u8 pad_38[0xC];
    f32 unk_44;  // 0 loads, 4 stores
    u8 pad_48[0x18];
    u32 unk_60;  // 2 loads, 0 stores
    u8 pad_64[0x19C];
} Obj_10_bss_5197C;
extern Obj_10_bss_5197C lbl_10_bss_5197C;

// lbl_10_data_454: .data size 0x2, 3 refs from sel.c
extern s16 lbl_10_data_454;

// lbl_10_bss_4938F: .bss size 0x1, 3 refs from sel.c
extern u8 lbl_10_bss_4938F;

// lbl_10_bss_49390: .bss size 0x10, 3 refs from sel.c
typedef struct {
    u8 unk_0;  // 2 loads, 2 stores
    u8 pad_1[0xF];
} Obj_10_bss_49390;
extern Obj_10_bss_49390 lbl_10_bss_49390;

// lbl_10_bss_517EC: .bss size 0x190, 3 refs from sel.c
typedef struct {
    u8 pad_0[0x44];
    f32 unk_44;  // 0 loads, 2 stores
    u8 pad_48[0x148];
} Obj_10_bss_517EC;
extern Obj_10_bss_517EC lbl_10_bss_517EC;

// lbl_10_data_2B4: .data size 0x1A0, 3 refs from sel.c
extern u8 lbl_10_data_2B4[0x1A0];

// lbl_10_bss_55670: .bss size 0x10, 3 refs from sel.c
typedef struct {
    u32 unk_0;  // 4 loads, 1 stores
    u8 pad_4[0xC];
} Obj_10_bss_55670;
extern Obj_10_bss_55670 lbl_10_bss_55670;

// lbl_10_bss_49384: .bss size 0x4, 2 refs from sel.c
extern u32 lbl_10_bss_49384;

// lbl_10_data_1038: .data size 0x4, 2 refs from sel.c (own data block)
extern u32 lbl_10_data_1038;

// lbl_10_bss_51752: .bss size 0x36, 2 refs from sel.c
typedef struct {
    u16 unk_0;  // 2 loads, 0 stores
    u8 pad_2[0x34];
} Obj_10_bss_51752;
extern Obj_10_bss_51752 lbl_10_bss_51752;

// lbl_10_bss_51750: .bss size 0x1, 2 refs from sel.c
extern u8 lbl_10_bss_51750;

// lbl_10_data_4AF8: .data size 0x2B8, 2 refs from sel.c (own data block)
typedef struct {
    u32 unk_0;  // 12 loads, 0 stores
    u8 pad_4[0x2B4];
} Obj_10_data_4AF8;
extern Obj_10_data_4AF8 lbl_10_data_4AF8;

// lbl_10_data_554: .data size 0x8, 2 refs from sel.c
extern s16 lbl_10_data_554;

// lbl_10_data_55C: .data size 0x8, 2 refs from sel.c
extern u32 lbl_10_data_55C;

// lbl_10_data_45A: .data size 0x6, 2 refs from sel.c
extern s16 lbl_10_data_45A;

// lbl_10_bss_55B04: .bss size 0x2C, 2 refs from sel.c
typedef struct {
    s16 unk_0;  // 1 loads, 0 stores
    s16 unk_2;  // 1 loads, 0 stores
    s16 unk_4;  // 1 loads, 0 stores
    s16 unk_6;  // 1 loads, 0 stores
    u8 pad_8[0x24];
} Obj_10_bss_55B04;
extern Obj_10_bss_55B04 lbl_10_bss_55B04;

// lbl_10_bss_55CDC: .bss size 0x1, 2 refs from sel.c
extern u8 lbl_10_bss_55CDC;

// lbl_10_bss_5565C: .bss size 0x8, 2 refs from sel.c
extern u32 lbl_10_bss_5565C;

// lbl_10_bss_5566C: .bss size 0x1, 2 refs from sel.c
extern u8 lbl_10_bss_5566C;

// lbl_10_data_1E80: .data size 0x330, 2 refs from sel.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x32C];
} Obj_10_data_1E80;
extern Obj_10_data_1E80 lbl_10_data_1E80;

// lbl_10_data_456: .data size 0x2, 2 refs from sel.c
extern s16 lbl_10_data_456;

// lbl_10_bss_55AE4: .bss size 0x20, 2 refs from sel.c
typedef struct {
    s16 unk_0;  // 1 loads, 0 stores
    s16 unk_2;  // 1 loads, 0 stores
    s16 unk_4;  // 1 loads, 0 stores
    s16 unk_6;  // 1 loads, 0 stores
    u8 pad_8[0x18];
} Obj_10_bss_55AE4;
extern Obj_10_bss_55AE4 lbl_10_bss_55AE4;

// lbl_10_bss_55668: .bss size 0x4, 2 refs from sel.c
extern u32 lbl_10_bss_55668;

// lbl_10_data_2CDC: .data size 0x388, 2 refs from sel.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 0 stores
    u8 pad_4[0x384];
} Obj_10_data_2CDC;
extern Obj_10_data_2CDC lbl_10_data_2CDC;

// lbl_10_data_578: .data size 0x4, 2 refs from sel.c
extern u32 lbl_10_data_578;

// lbl_10_data_6004: .data size 0x3, 1 refs from sel.c (own data block)
extern u32 lbl_10_data_6004;

// lbl_10_data_7B0: .data size 0x3C, 1 refs from sel.c (own data block)
typedef struct {
    u32 unk_0;  // 2 loads, 1 stores
    u8 pad_4[0x38];
} Obj_10_data_7B0;
extern Obj_10_data_7B0 lbl_10_data_7B0;

// jumptable_10_data_67E0: .data size 0x1C, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_67E0[0x1C];

// lbl_10_data_744: .data size 0x12, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_744[0x12];

// lbl_10_data_65C: .data size 0x20, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_65C[0x20];

// lbl_10_data_5EBC: .data size 0x2, 1 refs from sel.c (own data block)
extern u16 lbl_10_data_5EBC;

// jumptable_10_data_5EC: .data size 0x30, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_5EC[0x30];

// lbl_10_data_5E4: .data size 0x6, 1 refs from sel.c (own data block)
extern u32 lbl_10_data_5E4;

// lbl_10_data_694: .data size 0xE, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_694[0xE];

// jumptable_10_data_678C: .data size 0x54, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_678C[0x54];

// lbl_10_data_7A0: .data size 0xF, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_7A0[0xF];

// lbl_10_data_908: .data size 0x3F8, 1 refs from sel.c (own data block)
typedef struct {
    u8 pad_0[0x20];
    u32 unk_20;  // 1 loads, 0 stores
    u32 unk_24;  // 1 loads, 0 stores
    u32 unk_28;  // 1 loads, 0 stores
    u8 pad_2C[0x3CC];
} Obj_10_data_908;
extern Obj_10_data_908 lbl_10_data_908;

// jumptable_10_data_84C: .data size 0x30, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_84C[0x30];

// jumptable_10_data_6B0: .data size 0x20, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_6B0[0x20];

// lbl_10_data_788: .data size 0x16, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_788[0x16];

// lbl_10_data_5EC0: .data size 0x20, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_5EC0[0x20];

// lbl_10_data_5EE0: .data size 0x1D, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_5EE0[0x1D];

// lbl_10_data_6FC: .data size 0x48, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_6FC[0x48];

// jumptable_10_data_6D0: .data size 0x20, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_6D0[0x20];

// lbl_10_data_8F4: .data size 0x13, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_8F4[0x13];

// lbl_10_data_6008: .data size 0x14, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_6008[0x14];

// lbl_10_data_758: .data size 0x14, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_758[0x14];

// lbl_10_data_5E24: .data size 0x8, 1 refs from sel.c (own data block)
typedef struct {
    u32 unk_0;  // 1 loads, 0 stores
    u32 unk_4;  // 1 loads, 0 stores
} Obj_10_data_5E24;
extern Obj_10_data_5E24 lbl_10_data_5E24;

// lbl_10_data_5E4C: .data size 0x70, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_5E4C[0x70];

// jumptable_10_data_8AC: .data size 0x30, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_8AC[0x30];

// lbl_10_data_61C: .data size 0xC, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_61C[0xC];

// jumptable_10_data_628: .data size 0x34, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_628[0x34];

// lbl_10_data_5E2C: .data size 0x8, 1 refs from sel.c (own data block)
extern u32 lbl_10_data_5E2C;

// jumptable_10_data_7EC: .data size 0x20, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_7EC[0x20];

// lbl_10_data_67C: .data size 0x17, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_67C[0x17];

// jumptable_10_data_5FA0: .data size 0x30, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_5FA0[0x30];

// lbl_10_data_6A4: .data size 0xB, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_6A4[0xB];

// lbl_10_data_59C: .data size 0x48, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_59C[0x48];

// jumptable_10_data_87C: .data size 0x30, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_87C[0x30];

// lbl_10_data_76C: .data size 0x19, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_76C[0x19];

// lbl_10_data_8DC: .data size 0x16, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_8DC[0x16];

// jumptable_10_data_67FC: .data size 0x50, 1 refs from sel.c (own data block)
extern u8 jumptable_10_data_67FC[0x50];

// lbl_10_data_5F00: .data size 0x1C, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_5F00[0x1C];

// lbl_10_data_5F1C: .data size 0x84, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_5F1C[0x84];

// lbl_10_data_6280: .data size 0x14, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_6280[0x14];

// lbl_10_data_6294: .data size 0x10, 1 refs from sel.c (own data block)
extern u8 lbl_10_data_6294[0x10];

#endif  // REL_SEL_SEL_H
