#ifndef REL_REPLAY_REPLAY_MODE_H
#define REL_REPLAY_REPLAY_MODE_H

#include "types.h"
#include "rel/replay/globals.h"

// Generated by `fzgx headers --module replay --tu replay_mode.c`: globals of replay_mode.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_13_bss_0: .bss size 0x4, 3 refs from replay_mode.c
extern u32 lbl_13_bss_0;

// lbl_13_data_48: .data size 0xE, 2 refs from replay_mode.c (own data block)
extern u8 lbl_13_data_48[0xE];

// lbl_13_data_98: .data size 0x18, 1 refs from replay_mode.c (own data block)
extern u8 lbl_13_data_98[0x18];

#endif  // REL_REPLAY_REPLAY_MODE_H
