#ifndef REL_CAR_COLCHG_CAR_COLCHG_H
#define REL_CAR_COLCHG_CAR_COLCHG_H

#include "types.h"
#include "rel/car_colchg/globals.h"

// Generated by `fzgx headers --module car_colchg --tu car_colchg.c`: globals of car_colchg.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

#endif  // REL_CAR_COLCHG_CAR_COLCHG_H
