#ifndef REL_INTERVIEW_GLOBALS_H
#define REL_INTERVIEW_GLOBALS_H

#include "types.h"

// Generated by `fzgx headers --module interview`: layouts recovered from every access in the
// module's disassembly (matched or not). Field names are offsets until the librarian names them;
// offsets and widths are facts, names are not. Regenerate rather than hand-edit padding.

// lbl_17_bss_0: .bss size 0x1, referenced by 33 functions, shape {'object': 643}
extern u8 lbl_17_bss_0;

// lbl_17_data_0: .data size 0x1A4, referenced by 25 functions, shape {'object': 6}
typedef struct {
    u8 pad_0[0x1C];
    f32 unk_1C;  // 3 loads, 3 stores
    u8 pad_20[0x184];
} Obj_17_data_0;
extern Obj_17_data_0 lbl_17_data_0;

#endif  // REL_INTERVIEW_GLOBALS_H
