#ifndef REL_INTERVIEW_INTERVIEW_H
#define REL_INTERVIEW_INTERVIEW_H

#include "types.h"
#include "rel/interview/globals.h"

// Generated by `fzgx headers --module interview --tu interview.c`: globals of interview.c (referenced by its
// functions or living in its .data block), layouts recovered from every access in the module.

// lbl_17_bss_D8: .bss size 0x22, 14 refs from interview.c
typedef struct {
    u8 pad_0[0x18];
    u32 unk_18;  // 2 loads, 2 stores
    u8 pad_1C[0x6C];
    u32 unk_88;  // 13 loads, 0 stores
    u8 pad_8C[0x1C];
    f32 unk_A8;  // 0 loads, 5 stores
    f32 unk_AC;  // 0 loads, 5 stores
    f32 unk_B0;  // 0 loads, 5 stores
} Obj_17_bss_D8_At0;
typedef struct {
    u8 pad_0[0xA8];
    f32 unk_A8;  // 0 loads, 8 stores
    f32 unk_AC;  // 0 loads, 8 stores
    f32 unk_B0;  // 0 loads, 8 stores
} Obj_17_bss_D8_At8;
typedef struct {
    u8 pad_0[0xC];
    s16 unk_C;  // 1 loads, 0 stores
    u8 pad_E[0x9A];
    f32 unk_A8;  // 0 loads, 5 stores
    f32 unk_AC;  // 0 loads, 5 stores
    f32 unk_B0;  // 0 loads, 5 stores
} Obj_17_bss_D8_AtC;
typedef struct {
    Obj_17_bss_D8_At0 *unk_0;  // 22 loads, 1 stores
    u32 unk_4;  // 2 loads, 0 stores
    Obj_17_bss_D8_At8 *unk_8;  // 10 loads, 0 stores
    Obj_17_bss_D8_AtC *unk_C;  // 5 loads, 0 stores
    u8 pad_10[0x12];
} Obj_17_bss_D8;
extern Obj_17_bss_D8 lbl_17_bss_D8;

// lbl_17_data_63E50: .data size 0x250, 7 refs from interview.c (own data block)
extern u8 lbl_17_data_63E50[0x250];

// lbl_17_data_63BD0: .data size 0x150, 4 refs from interview.c
typedef struct {
    u8 pad_0[0xB0];
    u32 unk_B0;  // 1 loads, 0 stores
    u32 unk_B4;  // 1 loads, 0 stores
    u32 unk_B8;  // 1 loads, 0 stores
    u32 unk_BC;  // 1 loads, 0 stores
    u32 unk_C0;  // 1 loads, 0 stores
    u32 unk_C4;  // 1 loads, 0 stores
    u32 unk_C8;  // 1 loads, 0 stores
    u32 unk_CC;  // 1 loads, 0 stores
    u32 unk_D0;  // 1 loads, 0 stores
    u8 pad_D4[0x7C];
} Obj_17_data_63BD0;
extern Obj_17_data_63BD0 lbl_17_data_63BD0;

// lbl_17_data_63D20: .data size 0xFC, 4 refs from interview.c
typedef struct {
    u8 pad_0[0x80];
    u32 unk_80;  // 1 loads, 0 stores
    u32 unk_84;  // 1 loads, 0 stores
    u32 unk_88;  // 1 loads, 0 stores
    u32 unk_8C;  // 1 loads, 0 stores
    u32 unk_90;  // 1 loads, 0 stores
    u32 unk_94;  // 1 loads, 0 stores
    u32 unk_98;  // 1 loads, 0 stores
    u32 unk_9C;  // 1 loads, 0 stores
    u32 unk_A0;  // 1 loads, 0 stores
    u8 pad_A4[0x58];
} Obj_17_data_63D20;
extern Obj_17_data_63D20 lbl_17_data_63D20;

// lbl_17_bss_60: .bss size 0x76, 4 refs from interview.c
typedef struct {
    u8 pad_0[0x84];
    s16 unk_84;  // 2 loads, 0 stores
    u8 pad_86[0x12];
    s16 unk_98;  // 2 loads, 0 stores
} Obj_17_bss_60_At14;
typedef struct {
    u32 unk_0;  // 3 loads, 0 stores
    u8 pad_4[0x8];
    s16 unk_C;  // 2 loads, 0 stores
    u8 pad_E[0x2];
    u32 unk_10;  // 1 loads, 0 stores
    Obj_17_bss_60_At14 *unk_14;  // 2 loads, 0 stores
    u8 pad_18[0x5E];
} Obj_17_bss_60;
extern Obj_17_bss_60 lbl_17_bss_60;

// lbl_17_data_63190: .data size 0xA40, 3 refs from interview.c
extern u8 lbl_17_data_63190[0xA40];

// lbl_17_bss_14: .bss size 0x4, 3 refs from interview.c
extern u32 lbl_17_bss_14;

// lbl_17_bss_18: .bss size 0x8, 3 refs from interview.c
extern u32 lbl_17_bss_18;

// lbl_17_bss_54: .bss size 0x4, 3 refs from interview.c
extern u32 lbl_17_bss_54;

// lbl_17_data_63058: .data size 0x44, 3 refs from interview.c
typedef struct {
    u8 pad_0[0x10];
    u32 unk_10;  // 1 loads, 0 stores
    u8 pad_14[0x14];
    u32 unk_28;  // 1 loads, 0 stores
    u8 pad_2C[0x4];
    u32 unk_30;  // 5 loads, 0 stores
    u8 pad_34[0x4];
    u32 unk_38;  // 3 loads, 0 stores
    u32 unk_3C;  // 2 loads, 0 stores
    u8 pad_40[0x4];
} Obj_17_data_63058;
extern Obj_17_data_63058 lbl_17_data_63058;

// lbl_17_bss_58: .bss size 0x8, 3 refs from interview.c
extern u32 lbl_17_bss_58;

// lbl_17_bss_D6: .bss size 0x2, 2 refs from interview.c
extern u16 lbl_17_bss_D6;

// lbl_17_bss_1: .bss size 0x1, 2 refs from interview.c
extern u8 lbl_17_bss_1;

// lbl_17_bss_170: .bss size 0x28, 2 refs from interview.c
typedef struct {
    u8 unk_0;  // 1 loads, 0 stores
    u8 pad_1[0x7];
    u32 unk_8;  // 0 loads, 1 stores
    u32 unk_C;  // 0 loads, 1 stores
    u32 unk_10;  // 0 loads, 1 stores
    f32 unk_14;  // 2 loads, 1 stores
    f32 unk_18;  // 1 loads, 0 stores
    s16 unk_1C;  // 1 loads, 0 stores
    s16 unk_1E;  // 1 loads, 1 stores
    s16 unk_20;  // 1 loads, 0 stores
    s16 unk_22;  // 1 loads, 0 stores
    s16 unk_24;  // 1 loads, 0 stores
    s16 unk_26;  // 1 loads, 0 stores
} Obj_17_bss_170;
extern Obj_17_bss_170 lbl_17_bss_170;

// lbl_17_data_64458: .data size 0x4, 2 refs from interview.c (own data block)
extern u32 lbl_17_data_64458;

// lbl_17_data_644E8: .data size 0x10, 1 refs from interview.c (own data block)
extern u8 lbl_17_data_644E8[0x10];

// lbl_17_data_644F8: .data size 0x66, 1 refs from interview.c (own data block)
extern u8 lbl_17_data_644F8[0x66];

// jumptable_17_data_6419C: .data size 0x28, 1 refs from interview.c (own data block)
extern u8 jumptable_17_data_6419C[0x28];

// lbl_17_data_640A0: .data size 0xB0, 1 refs from interview.c (own data block)
extern u8 lbl_17_data_640A0[0xB0];

// lbl_17_data_6437C: .data size 0xDC, 1 refs from interview.c (own data block)
extern u8 lbl_17_data_6437C[0xDC];

// lbl_17_data_64378: .data size 0x4, 1 refs from interview.c (own data block)
extern u32 lbl_17_data_64378;

// jumptable_17_data_64300: .data size 0x28, 1 refs from interview.c (own data block)
extern u8 jumptable_17_data_64300[0x28];

// lbl_17_data_6445C: .data size 0x8C, 1 refs from interview.c (own data block)
extern u8 lbl_17_data_6445C[0x8C];

// lbl_17_data_64150: .data size 0x4C, 1 refs from interview.c (own data block)
extern u8 lbl_17_data_64150[0x4C];

#endif  // REL_INTERVIEW_INTERVIEW_H
