/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/profile/data/lbl_16_data_82F28.h"

#include "rel/profile/data/lbl_16_data_82F28.h"


extern char lbl_16_data_82DB0[];
extern char lbl_16_data_82DB8[];
extern char lbl_16_data_82DC0[];
extern char lbl_16_data_82DD0[];
extern char lbl_16_data_82E10[];
extern char lbl_16_data_82E1C[];
extern char lbl_16_data_82E24[];
extern char lbl_16_data_82E48[];
extern char lbl_16_data_82E64[];
extern char lbl_16_data_82E78[];
extern char lbl_16_data_82E88[];
extern char lbl_16_data_82E98[];
extern char lbl_16_data_82EA8[];
extern char lbl_16_data_82EBC[];
extern char lbl_16_data_82ECC[];
extern char lbl_16_data_82EE8[];
extern char lbl_16_data_82F08[];
extern u8 lbl_16_data_82DB4[];
extern u8 lbl_16_data_82DEC[];
extern u8 lbl_16_data_82E3C[];
extern u8 lbl_16_data_82E54[];
extern u8 lbl_16_data_82E70[];
extern u8 lbl_16_data_82E80[];
extern u8 lbl_16_data_82E90[];
extern u8 lbl_16_data_82EA0[];
extern u8 lbl_16_data_82EB0[];
extern u8 lbl_16_data_82EC4[];
extern u8 lbl_16_data_82EDC[];
extern u8 lbl_16_data_82EF8[];
extern u8 lbl_16_data_82F18[];
#pragma explicit_zero_data on
__declspec(section ".data") Data_lbl_16_data_82F28 lbl_16_data_82F28 __attribute__((aligned(8))) = {
    (u8 *)&lbl_16_data_82DB0,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB0,
    (u8 *)&lbl_16_data_82DB8,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB8,
    (u8 *)&lbl_16_data_82DC0,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DC0,
    (u8 *)&lbl_16_data_82DD0,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DEC,
    (u8 *)&lbl_16_data_82E10,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E10,
    (u8 *)&lbl_16_data_82E1C,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E1C,
    (u8 *)&lbl_16_data_82E24,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E3C,
    (u8 *)&lbl_16_data_82E48,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E54,
    (u8 *)&lbl_16_data_82E64,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E70,
    (u8 *)&lbl_16_data_82E78,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E80,
    (u8 *)&lbl_16_data_82E88,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82E90,
    (u8 *)&lbl_16_data_82E98,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82EA0,
    (u8 *)&lbl_16_data_82EA8,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82EB0,
    (u8 *)&lbl_16_data_82EBC,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82EC4,
    (u8 *)&lbl_16_data_82ECC,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82EDC,
    (u8 *)&lbl_16_data_82EE8,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82EF8,
    (u8 *)&lbl_16_data_82F08,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82DB4,
    (u8 *)&lbl_16_data_82F18
};
#pragma explicit_zero_data reset
