/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/profile/data/lbl_16_data_82C1C.h"

extern char lbl_16_data_82BF8[36];
#include "rel/profile/data/lbl_16_data_82C1C.h"



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82BF8[36] __attribute__((aligned(8))) = "profile.c\000\000\000DrawOrdSys\000\000LightMain\000\000";
#pragma explicit_zero_data reset


extern void fn_16_1038(void);
extern void fn_16_14D4(void);
extern void fn_16_18CC(void);
extern void fn_16_1D18(void);
extern void fn_16_1F1C(void);
extern void fn_16_2054(void);
extern void fn_16_2328(void);
extern void fn_16_23A8(void);
extern void fn_16_24A4(void);
extern void fn_16_B24(void);
extern void fn_16_CAC(void);
extern void fn_16_DC8(void);
extern void fn_1_12B4(void);
extern void fn_1_12FC(void);
extern void fn_1_1300(void);
#pragma explicit_zero_data on
__declspec(section ".data") Data_lbl_16_data_82C1C lbl_16_data_82C1C __attribute__((aligned(4))) = {
    0x534D445FU,
    0x50524F46U,
    0x494C455FU,
    0x544F5000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_1_12B4,
    fn_1_12FC,
    fn_1_1300,
    0x534D445FU,
    0x50524F46U,
    0x494C455FU,
    0x4D454E55U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_16_B24,
    fn_16_CAC,
    fn_16_DC8,
    0x534D445FU,
    0x44524956U,
    0x45525F50U,
    0x524F4649U,
    0x4C450000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_16_1038,
    fn_16_14D4,
    fn_16_18CC,
    0x534D445FU,
    0x4D414348U,
    0x494E455FU,
    0x50524F46U,
    0x494C4500U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_16_1D18,
    fn_16_1F1C,
    fn_16_2054,
    0x534D445FU,
    0x4D4F5649U,
    0x455F5052U,
    0x4F46494CU,
    0x45000000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_16_2328,
    fn_16_23A8,
    fn_16_24A4,
    0x534D445FU,
    0x50524F46U,
    0x494C455FU,
    0x424F5454U,
    0x4F4D0000U,
    0x00000000U,
    0x00000000U,
    0x00000000U,
    fn_1_12B4,
    fn_1_12FC,
    fn_1_1300,
    0x76656869U,
    0x636C652FU,
    0x00000000U,
    0x2E2E0000U,
    0x526F6245U,
    0x78656300U
};
#pragma explicit_zero_data reset
