/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_16_data_82EE8[15];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82EE8[15] __attribute__((aligned(8))) = "Boost Strength";
#pragma explicit_zero_data reset
