/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/profile/data/lbl_16_bss_B0B8.h"

#include "rel/profile/data/lbl_16_bss_B0B8.h"



__declspec(section ".data") ProfileBiographyBuffer lbl_16_bss_B0B8 __attribute__((aligned(8)));
