/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_16_data_83500[33];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_83500[33] __attribute__((aligned(8))) = "c0x83ad %s c0x83a6 %s c0x83a0 %s";
#pragma explicit_zero_data reset
