/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/profile/data/lbl_16_data_82B34.h"

extern char lbl_16_data_82B10[9];
extern char lbl_16_data_82B1C[12];
extern char lbl_16_data_82B28[12];
#include "rel/profile/data/lbl_16_data_82B34.h"



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82B10[9] __attribute__((aligned(8))) = "SEL_WAIT";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82B1C[12] __attribute__((aligned(4))) = "SEL_WAIT_01";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82B28[12] __attribute__((aligned(8))) = "SEL_WAIT_02";
#pragma explicit_zero_data reset





#pragma explicit_zero_data on
__declspec(section ".data") Data_lbl_16_data_82B34 lbl_16_data_82B34 __attribute__((aligned(4))) = {
    (u8 *)&lbl_16_data_82B10,
    (u8 *)&lbl_16_data_82B10,
    (u8 *)&lbl_16_data_82B10,
    (u8 *)&lbl_16_data_82B1C,
    (u8 *)&lbl_16_data_82B10,
    (u8 *)&lbl_16_data_82B10,
    (u8 *)&lbl_16_data_82B10,
    (u8 *)&lbl_16_data_82B28
};
#pragma explicit_zero_data reset
