/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_16_data_82E48[11];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82E48[11] __attribute__((aligned(8))) = "View Movie";
#pragma explicit_zero_data reset
