/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_16_data_82E10[11];
extern char lbl_16_data_82E1C[8];
extern char lbl_16_data_82E24[22];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82E10[11] __attribute__((aligned(8))) = "PILOT DATA";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82E1C[8] __attribute__((aligned(4))) = "MACHINE";
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82E24[22] __attribute__((aligned(4))) = "Machine Introductions";
#pragma explicit_zero_data reset
