/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"
#include "rel/profile/data/lbl_16_rodata_58.h"
#include "rel/profile/data/lbl_16_rodata_AC.h"

extern const f32 lbl_16_rodata_0[18];
extern const f32 lbl_16_rodata_48[4];
#include "rel/profile/data/lbl_16_rodata_58.h"
#include "rel/profile/data/lbl_16_rodata_AC.h"
extern const u32 lbl_16_rodata_1DC[24];



#pragma explicit_zero_data on
__declspec(section ".rodata") const f32 lbl_16_rodata_0[18] __attribute__((aligned(4))) = {
    0.0f, 0.0f, 320.0f, 240.0f, 0.00100000005f, 0.00999999978f, 0.5f, 480.0f, 2.0f, 0.0f, 176.0f, 0.0f, -4.5f, -17.5f, -2.9000001f, 30.0f, 0.87843138f, -11.0f
};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const f32 lbl_16_rodata_48[4] __attribute__((aligned(4))) = {
    1.0f, 0.625f, -30.0f, -6.0f
};
#pragma explicit_zero_data reset


/* Preserve non-finite payloads and signed zero without compiler canonicalization. */
#pragma explicit_zero_data on
__declspec(section ".rodata") const Data_lbl_16_rodata_58 lbl_16_rodata_58 __attribute__((aligned(4))) = {{
    0xFFFF0000U, 0x41A00000U, 0x41200000U, 0x3F19999AU, 0x43E40000U, 0x3E000000U, 0x40A00000U, 0x3FB8E38EU, 0x3F800000U, 0x42380000U, 0x42500000U, 0x3F000000U, 0x428E0000U, 0x41B00000U, 0x42C40000U, 0x42BAC6C7U, 0x3F44C4C5U, 0x00000000U, 0x43300000U, 0x80000000U, 0xFFFF0000U
}};
#pragma explicit_zero_data reset


/* Preserve non-finite payloads and signed zero without compiler canonicalization. */
#pragma explicit_zero_data on
__declspec(section ".rodata") const Data_lbl_16_rodata_AC lbl_16_rodata_AC __attribute__((aligned(4))) = {{
    0x00000000U, 0x42000000U, 0x41E00000U, 0x428A0000U, 0x43A90000U, 0x43FC0000U, 0x41C00000U, 0x41000000U, 0x3F471C72U, 0x429E0000U, 0x43AB8000U, 0x431B0000U, 0x43B68000U, 0xFFFF0000U, 0x42300000U, 0x43780000U, 0x40C00000U, 0xFFFF0000U, 0x43F00000U, 0x430E0000U, 0x436C0000U, 0x42CC0000U, 0x42D60000U, 0x3F200000U, 0x430D0000U, 0x40E00000U, 0x43360B61U, 0x43340000U, 0x43060000U, 0x3DCCCCCDU, 0x3F40C0C1U, 0x3E99999AU, 0x43B40000U, 0x43300000U, 0x00000000U, 0xFFFF0000U, 0x41980000U, 0x41880000U, 0x42960000U, 0x42B80000U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x3F400000U, 0x42140000U, 0x42940000U, 0x41D00000U, 0x427C0000U, 0x428C0000U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x00FFFF00U, 0x43A00000U, 0x43580000U, 0x42F40000U, 0x43480000U, 0x43980000U, 0x42200000U, 0x44160000U, 0x3DCCCCD0U, 0x3EAE147AU, 0xC2CC0000U, 0x3F666666U, 0x3F28F5C3U, 0x3F638E39U, 0x42BE0000U, 0x40000000U, 0x423C0000U, 0x41800000U
}};
#pragma explicit_zero_data reset



#pragma explicit_zero_data on
__declspec(section ".rodata") const u32 lbl_16_rodata_1DC[24] __attribute__((aligned(4))) = {
    0x00000000U, 0x00000000U, 0x00000000U, 0x43DC0000U, 0x43F20000U, 0x40400000U, 0x3FCCCCCDU, 0x43700000U, 0x43960000U, 0x42600000U, 0x3F2AAAABU, 0x41100000U, 0x41300000U, 0x41600000U, 0x41400000U, 0x41700000U, 0x41500000U, 0x41900000U, 0x3D4CCCCDU, 0x00000000U, 0x00000000U, 0x00000000U, 0x3FAB851FU, 0xC28C0000U
};
#pragma explicit_zero_data reset
