/* Generated by fzgx data-import; provenance in state/dataimports/. */
#include "types.h"

extern char lbl_16_data_82EA8[7];



#pragma explicit_zero_data on
__declspec(section ".data") char lbl_16_data_82EA8[7] __attribute__((aligned(8))) = "Engine";
#pragma explicit_zero_data reset
